### ISSUE TITLE
sendMessage() のバグ

### ISSUE THREAD

**Issue by Nerahikada** [BlueLightJapan/BlueLight#101]
> `$player->sendMessage("test");`
> `$player->sendMessage("foo");`
> `$player->sendMessage("bar");`

プレイヤーからはこのように表示されます。

> `test`
> `test`
> `foo`
> `test`
> `foo`
> `bar`

**Comment by erkam2002** [comment]
Its a client bug..

**Comment by Nerahikada** [comment]
Thanks :)

**Comment by Nerahikada** [comment]
oh... thanks :)

#32 と同じでした…
