### ISSUE TITLE
Error on crafting wood and workbench in my inventory

### ISSUE THREAD

**Issue by jeremy100** [BlueLightJapan/BlueLight#109]
Server response:

Notice: Undefined offset: 0 in phar://D:/Minecraft/*******/******* Pocket Edition 1.0.0/Installation-Binariesx86-master/BlueLight-PHP7.phar/src/pocketmine/Player.php on line 3028

**Comment by haniokasai** [comment]
#108

**Comment by kametan0730MC** [comment]
Fixed

**Comment by jeremy100** [comment]
Thanks! :)
