### ISSUE TITLE
Not Restart!

### ISSUE THREAD

**Issue by popkechupki** [BlueLightJapan/BlueLight#116]
start.shでDO_LOOPをyesに設定しても再起動しません。

**Comment by haniokasai** [comment]
please try it https://github.com/pmmp/PocketMine-MP/blob/master/start.sh

**Comment by popkechupki** [comment]
できません…

**Comment by haniokasai** [comment]
うーん

**Comment by popkechupki** [comment]
どうしたらいいですか...

**Comment by haniokasai** [comment]
srcは関係ないはずなんだけどな、、、

**Comment by popkechupki** [comment]
少し前のClearSkyではできたんでは今では他のでもできないんですよ...

**Comment by kametan0730MC** [comment]
公式とマージしたので多分できます
