### ISSUE TITLE
virtualgladiators say that we that we are very promising

### ISSUE THREAD

**Issue by caspervanneck** [BlueLightJapan/BlueLight#119]
virtualgladiators say: So here it is a week later and we are all still waiting for a proper, stable release of Pocketmine v1.0. Elywing is the only build that has been releasing 1.0 compatible updates, but they are extremely buggy! ***2016-12-29 UPDATE: BlueLight is another 1.0 compatible build from a small group of Japanese developers that looks very promising. EssentialsPE MUST BE UPGRADED if you...

**Comment by caspervanneck** [comment]
so keep it up team 🥇 👍

**Comment by NemanjaMAX** [comment]
@caspervanneck nope,wrong answer
Github.com/TesseractTeam/Tesseract they are stablest.
Its new name of ImagicalMine (Inactive-To-Reactive)

**Comment by caspervanneck** [comment]
@NemanjaMAX  you're wrong. Genisys is always unstable (ande it forks and spoons)
