### ISSUE TITLE
How to manage MySQL data

### ISSUE THREAD

**Issue by haniokasai** [BlueLightJapan/BlueLight#12]
プリペアステートメント使わないと、sqlインジェクションられるんじゃね？

**Comment by kametan0730MC** [comment]
別に鯖内からしか送らないし、フォームとかから処理しないし大丈夫じゃない？

**Comment by haniokasai** [comment]
大丈夫かな。。。
setcustomname悪用できない？

**Comment by haniokasai** [comment]
あとポートは,19132じゃない3306

**Comment by haniokasai** [comment]
saveinventoryの処理、相当重いぞこれ

**Comment by kametan0730MC** [comment]
僕の鯖でやってたけど大丈夫だったよ
