### ISSUE TITLE
Suport for mcpe beta 1.0.3

### ISSUE THREAD

**Issue by caspervanneck** [BlueLightJapan/BlueLight#128]
Is at the 1.0.3 branch @haniokasai tell The all (team) plz help i can do it on my one

**Comment by haniokasai** [comment]
im not leader lol

**Comment by caspervanneck** [comment]
OK sorry lol @haniokasai

**Comment by haniokasai** [comment]
@caspervanneck i told it all member! but @Ogiwara-CostlierRain464  cant use pc because he may study something, @famima65536 dont have android :(
im free,but i dont understand about src (-.-;)

**Comment by haniokasai** [comment]
@kametan0730MC how about you?

**Comment by BlawoHD** [comment]
Add TransferCommand?

**Comment by kametan0730MC** [comment]
夜じゅうにobjdumpしとく

**Comment by AppleDevelops** [comment]
Originality?

**Comment by Herojhjh** [comment]
login timeout?

**Comment by AppleDevelops** [comment]
@Herojhjh It's what happens when you steal code

**Comment by Herojhjh** [comment]
@AppleDevelops steal?i download from BlueLight github

**Comment by caspervanneck** [comment]
@AppleDevelops  you steal from Apollo so your generator  is stolen

**Comment by AppleDevelops** [comment]
Apollo? What's Apollo? I can get your repo suspended for taking copyrighted code.

**Comment by AppleDevelops** [comment]
@caspervanneck Tesseract contains no code from Apollo, I've never heard of it until now. One thing if you are going to use Tesseract's code for BlueLight's benefit, at least give credit or you are violating our license.

**Comment by caspervanneck** [comment]
@AppleDevelops 4f57817  i done it

**Comment by AppleDevelops** [comment]
@caspervanneck Much better than you

**Comment by BlawoHD** [comment]
MCPE 1.0.3 version is out

**Comment by BlawoHD** [comment]
795dbbf
