### ISSUE TITLE
mcregion

### ISSUE THREAD

**Issue by HIKARU0412KOZAKI** [BlueLightJapan/BlueLight#131]
### Issue description
Write a short description about the issue

mcregionが読み込まれない

### Steps to reproduce the issue

mcregionが読み込めない

### OS and versions

* BlueLight: ?
* PHP: 7
* Server OS: Win10x64
* Game version: 1.0.0

**Comment by haniokasai** [comment]
https://github.com/BlueLightJapan/BlueLight/issues/137
