### ISSUE TITLE
Enchantments doesn't work

### ISSUE THREAD

**Issue by NiclasQueen** [BlueLightJapan/BlueLight#135]
### Issue description
Enchantments doesn't work

**Comment by caspervanneck** [comment]
@kametan0730MC when will this be added

**Comment by kametan0730MC** [comment]
Some days later

**Comment by BlawoHD** [comment]
@kametan0730MC Finished?

**Comment by caspervanneck** [comment]
@kametan0730MC  doese it work

**Comment by caspervanneck** [comment]
and why am out of team -_-

**Comment by kametan0730MC** [comment]
https://github.com/BlueLightJapan/BlueLight/commit/44b4abf3b25b276e7e9c1c1eb0a2f9bb52d5cc02

**Comment by kametan0730MC** [comment]
Because you are copying files directly from other src

**Comment by kametan0730MC** [comment]
I wanted you to fit a bit more Packet etc according to file from the original

**Comment by kametan0730MC** [comment]
If you want, I will return you to the team

**Comment by caspervanneck** [comment]
@kametan0730MC yes i wnt to return

**Comment by caspervanneck** [comment]
@kametan0730MC  can i return? i want it

**Comment by kametan0730MC** [comment]
Ok

**Comment by YaBoiDevelops** [comment]
EAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCK

**Comment by KromeThirty30** [comment]
@kametan0730MC Please fix the enchantment table :) items dropped and the items that i enchant goes to normal

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
