### ISSUE TITLE
Work this now?

### ISSUE THREAD

**Issue by erkam2002** [BlueLightJapan/BlueLight#14]
Work this serversoftware?

**Comment by haniokasai** [comment]
yeah,of cource

**Comment by erkam2002** [comment]
How can i get php binarys for this if i use this for Genisys i become an error can you please give me a ljnk?

**Comment by haniokasai** [comment]
please downlod bin from bintray.

**Comment by erkam2002** [comment]
yes it works thx

**Comment by haniokasai** [comment]
good!
