### ISSUE TITLE
Cant change hotbar blocks

### ISSUE THREAD

**Issue by RompeCraneos** [BlueLightJapan/BlueLight#143]
### Issue description
Blocks missing when i place it

### Steps to reproduce the issue
Put block in your hand and try to place

### OS and versions
* BlueLight: PocketMine-MP-DerivedVersion version 2.0dev "BlueLight" (API 3.0.0)
* PHP: 7
* Server OS: windows10
* Game version: windows10 and MCPE 1.0.3

### Crashdump, backtrace or other files

* ...

**Comment by kametan0730MC** [comment]
fixed
