### ISSUE TITLE
Furnace not work

### ISSUE THREAD

**Issue by TanToan99** [BlueLightJapan/BlueLight#144]
Issue description

cant use this item Furnace
![16731361_255488674893260_230494248_o](https://cloud.githubusercontent.com/assets/23021197/22852460/462d993c-f06f-11e6-9ad5-aa1c715f9da4.jpg)

Steps to reproduce the issue

use item Furnace

OS and versions

BlueLight: PocketMine-MP-DerivedVersion version 2.0dev "BlueLight" (API 3.0.0)
PHP: 7
Server OS: linux
Game version: MCPE 1.0.3
Crashdump, backtrace or other files
nothing
...

**Comment by BlawoHD** [comment]
On my server works the Furnace.

**Comment by kametan0730MC** [comment]
fixed

**Comment by InquisitionCraft** [comment]
What version do you need to be on for it to work?
