### ISSUE TITLE
Support all v1.0.x

### ISSUE THREAD

**Issue by BlawoHD** [BlueLightJapan/BlueLight#148]
Do we like [Lifeboat](https://github.com/Hydreon/Steadfast2) that you can join on any 1.0.x version?

**Comment by RompeCraneos** [comment]
You can change edit network values for it, but isnt recommended

**Comment by Qimie** [comment]
Im prtty sure you cant do that. Because only mcpe 1.0.3 has TransferPacket. 1.0.2 and below doesnt has TransferPacket implemented.

**Comment by RompeCraneos** [comment]
This was added to my Server, when player of 1.0.2 use command for transfer nothing occurs, but working good to play with these versions

**Comment by kametan0730MC** [comment]
I do not think that it is necessary.
