### ISSUE TITLE
FIX >>> TRANSFER PERMISSION

### ISSUE THREAD

**Issue by NiclasQueen** [BlueLightJapan/BlueLight#151]
### Issue description
Add Transfer Permission

### FIX

	  public function execute(CommandSender $sender, $currentAlias, array $args){
		if($sender instanceof Player){
if($sender->hasPermission("pocketmine.command.tranfer")) {
			if(isset($args[1])){
				$port = $args[1];
			}else{
				$port = 19132;
			}
        		$pk = new TransferPacket();
        		$pk->address = $args[0];
        		$pk->port = $port;
        		$sender->dataPacket($pk);
        		Command::broadcastCommandMessage($sender, "Transferred to " . $args[0] . ":" . $port);
                        }else{
                            $sender->sendMessage("You have no Permission to use this Command!");
                        }
			
		}else{
			$sender->sendMessage("Run this command in game!");
		}
    }
}

**Comment by caspervanneck** [comment]
spam

**Comment by caspervanneck** [comment]
we know that it need a fix

**Comment by caspervanneck** [comment]
fix #149

**Comment by NiclasQueen** [comment]
Bruh i made the fix

**Comment by caspervanneck** [comment]
@NiclasQueen  i dont say it from my
