### ISSUE TITLE
Boat is following me

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#155]
Bluelight:1d1405b
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

When you leave from the boat,is like this:
![screenshot_2017-02-16-21-27-11](https://cloud.githubusercontent.com/assets/22281205/23037711/194d5ef0-f490-11e6-997d-07802ef8ff01.png)

![screenshot_2017-02-16-21-26-59](https://cloud.githubusercontent.com/assets/22281205/23037762/3bedb630-f490-11e6-9725-0e63c3fed0ba.png)

**Comment by poustmal** [comment]
and you can't take it from your head.

**Comment by BlawoHD** [comment]
lol

**Comment by haniokasai** [comment]
lol

**Comment by poustmal** [comment]
._.

**Comment by kametan0730MC** [comment]
I  will fix it.

**Comment by kametan0730MC** [comment]
fixed
