### ISSUE TITLE
Linux Error on start

### ISSUE THREAD

**Issue by erkam2002** [BlueLightJapan/BlueLight#16]
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory

**Comment by haniokasai** [comment]
hmm... it is not bluelight bug.

**Comment by erkam2002** [comment]
What then?

**Comment by haniokasai** [comment]
please try to download from bintray.

**Comment by erkam2002** [comment]
ok
