### ISSUE TITLE
Chest not working 

### ISSUE THREAD

**Issue by InquisitionCraft** [BlueLightJapan/BlueLight#166]
### Issue description
Write a short description about the issue
Chests are not working items lag out look like they're staying in then your inventory lags and they're back in your inventory
### Steps to reproduce the issue

1...place a chest 

2...put item in chest 
3...throw item from inventory 
4..items should be out from chests and in your inventory 

### OS and versions

* BlueLight:
* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by kametan0730MC** [comment]
Are you using the latest version?

**Comment by InquisitionCraft** [comment]
Yes we are and its still not working.

**Comment by BlawoHD** [comment]
Lol, but it works for me

**Comment by caspervanneck** [comment]
alredy fixt
