### ISSUE TITLE
Player.php Crash

### ISSUE THREAD

**Issue by BlawoHD** [BlueLightJapan/BlueLight#167]
### OS and versions

* BlueLight: 
* PHP: 7.0.9
* Server OS: Linux
* Game version: 1.0.3

### Crashdump, backtrace or other files

Error: Object of class stdClass could not be converted to string
File: /src/pocketmine/Player
Line: 3026
Type: E_RECOVERABLE_ERROR

Code:

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

**Comment by caspervanneck** [comment]
yes i try to fix dat @BlawoHD
