### ISSUE TITLE
Unloading level "world" から進まない

### ISSUE THREAD

**Issue by Nerahikada** [BlueLightJapan/BlueLight#172]
### Issue description
ワールドを新規作成して、サーバーを止めると、Unloading level から進まない

### Steps to reproduce the issue

1... ワールドを新規作成して、サーバーを止める

### OS and versions
* BlueLight: 5dc9388
* PHP: 7.0.2
* Server OS: Windows 10
* Game version: 1.0.3 alpha

### Crashdump, backtrace or other files
* Console:
︙
[Server thread/NOTICE]: Level "world" not found
[Server thread/INFO]: Preparing level "world"
[Server thread/NOTICE]: Spawn terrain for level "world" is being generated in the background
[Server thread/INFO]: Default game type: Survival Mode
[Server thread/INFO]: Done (2.688s)! For help, type "help" or "?"
stop
[Server thread/INFO]: [CONSOLE: Stopping the server]
[Server thread/INFO]: Unloading level "world"

(いくら待っても進まない)

**Comment by Nerahikada** [comment]
プレイヤーがサーバーにログインして、ワールドを生成すると正常に止まります。

**Comment by Nerahikada** [comment]
新規作成でなくても、同じ現象が発生します。

**Comment by caspervanneck** [comment]
you use 1.0.4 branch i now that bug with the evel and its fixt

**Comment by caspervanneck** [comment]
@Nerahikada
