### ISSUE TITLE
BinaryStream.php - Uninitialized string offset: 4

### ISSUE THREAD

**Issue by Nerahikada** [BlueLightJapan/BlueLight#173]
### Steps to reproduce the issue
1... Loggin server

### OS and versions
* BlueLight: 5dc9388
* PHP: 7.0.2
* Server OS: Windows 10

### Crashdump, backtrace or other files
Notice: Uninitialized string offset: 4 in *\src\pocketmine\utils\BinaryStream.php on line 172

**Comment by caspervanneck** [comment]
outdated or unsuported build @Nerahikada
