### ISSUE TITLE
1.0.4beta SugarCane files

### ISSUE THREAD

**Issue by Nerahikada** [BlueLightJapan/BlueLight#174]
### Issue description
src\pocketmine\level\generator\populator\SugarCane.php
src\pocketmine\level\generator\populator\Sugarcane.php
It can't coexist on Windows.

### OS and versions
* Server OS: Windows 10

**Comment by AppleDevelops** [comment]
Are you stupid?

**Comment by Nerahikada** [comment]
Why?
