### ISSUE TITLE
On stop

### ISSUE THREAD

**Issue by erkam2002** [BlueLightJapan/BlueLight#18]
[Server thread/CRITICAL]: Error: "Call to a member function wait() on null" (EXCEPTION) in "/src/raklib/server/ServerHandler" at line 64
[10:55:49] [Server thread/EMERGENCY]: Crashed while crashing, killing process

**Comment by kametan0730MC** [comment]
When will the error come out?

**Comment by erkam2002** [comment]
if i write /stop

**Comment by kametan0730MC** [comment]
ok

**Comment by Ogiwara-CostlierRain464** [comment]
I've fixed it.
