### ISSUE TITLE
ADD Dragon Egg

### ISSUE THREAD

**Issue by GodNation** [BlueLightJapan/BlueLight#181]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1... I Need Dragon Egg For My Eggwars Plugin

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by kametan0730MC** [comment]
ok

**Comment by kametan0730MC** [comment]
finished

**Comment by BlawoHD** [comment]
#331
