### ISSUE TITLE
Mob AI's(Read Before Close)

### ISSUE THREAD

**Issue by Qimie** [BlueLightJapan/BlueLight#182]
So,when is Mob AIs is gonna be implemented? We r all waiting. No open source software has Mob AI working. Hopefully BlueLight will be the first and the only one. That will be written in history.

**Comment by twixi** [comment]
Waiting too!!

**Comment by haniokasai** [comment]
G**i*** 's Mob AI is not libre software :(

**Comment by haniokasai** [comment]
but,this Mob AIs plugin https://github.com/RevivalPMMP/PureEntitiesX/blob/master/LICENSE is libre plugin.
