### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by isoz** [BlueLightJapan/BlueLight#19]
I have weather set to false yet it still rains.

**Comment by kametan0730MC** [comment]
Fixed,Thank you for your report.

**Comment by isoz** [comment]
It wasn't fixed...

**Comment by haniokasai** [comment]
relly?check your src version,if it is latest,please report here.

**Comment by Ogiwara-CostlierRain464** [comment]
直ってない気がするよ

**Comment by Ogiwara-CostlierRain464** [comment]
・言語ファイルの設定がまだ
・そして天候を変えられない

言語ファイルはふぁみさんとかkenさんとかに直してほすいかも

**Comment by kametan0730MC** [comment]
まじすか、天気は直したんだが

**Comment by kametan0730MC** [comment]
I will check it.

**Comment by isoz** [comment]
It is the latest... Weather is set to false yet it rains all the time.

**Comment by kametan0730MC** [comment]
Ok

**Comment by kametan0730MC** [comment]
I fixed it

**Comment by kametan0730MC** [comment]
Please try it.

**Comment by Ogiwara-CostlierRain464** [comment]
There are still language bug, but it works.
