### ISSUE TITLE
WIN 10 Issue

### ISSUE THREAD

**Issue by Herojhjh** [BlueLightJapan/BlueLight#191]
I cant hold item in creative mode!

**Comment by kametan0730MC** [comment]
When I tried it, I could not confirm such a problem
Are you using the latest version?

**Comment by Herojhjh** [comment]
yes

**Comment by Herojhjh** [comment]
![image](https://cloud.githubusercontent.com/assets/21217348/24187101/1130711a-0f0e-11e7-9b34-91a8f04e5264.png)

**Comment by kametan0730MC** [comment]
When is it such a case?
Is it when given from the plug-in?

**Comment by kametan0730MC** [comment]
Is it when you take out yourself?

**Comment by MalakasPlayzMC** [comment]
I know the cause. You need to remove the bossbar plugin

**Comment by kametan0730MC** [comment]
Thanks.
