### ISSUE TITLE
a option for invertory cheating on or off

### ISSUE THREAD

**Issue by caspervanneck** [BlueLightJapan/BlueLight#194]
so enchenting shuld work then. like the option from genisys

**Comment by kametan0730MC** [comment]
ok

**Comment by kametan0730MC** [comment]
How to do?

**Comment by caspervanneck** [comment]
@kametan0730MC  maby copy genisys

**Comment by TDMidkwhatisxd** [comment]
inventory cheat off, actually allows toolbox to hack items, tested. Never add a option to turn it off.

**Comment by caspervanneck** [comment]
enchanting @TDMidkwhatisxd
