### ISSUE TITLE
sound bug

### ISSUE THREAD

**Issue by kamata4649** [BlueLightJapan/BlueLight#195]
### Issue description
サウンドがなりません。(Ver1.0.6)
### Steps to reproduce the issue

1. ブロックを破壊する, Block break sound
2. ブロックを設置する, Block set sound
3. 歩いたり落下したりなど, Walk or Run sound
4. ダメージ , Damage sound
5. 音ブロック, Note Sound

※ボタンなどの音はなります

### OS and versions

* PHP: 7.0.x(ClearSkybinary opcache)
* Server OS: CentOS7
* Game version: 1.0.6β

### Crashdump, backtrace or other files

* ...

**Comment by SuperXingKong** [comment]
I think it easy to fix, but noteblock still doesn't work.

**Comment by kametan0730MC** [comment]
Fixed, but noteblock still dont work

**Comment by kametan0730MC** [comment]
move to #354
