### ISSUE TITLE
Can't ride horses

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BlueLightJapan/BlueLight#197]
### Issue description
I can't ride horses and I have set in the bluelight.properties RideableEntity=off to on

**Comment by kametan0730MC** [comment]
confirm

**Comment by kametan0730MC** [comment]
I tried it with the latest version, but I could not find such a problem

**Comment by MalakasPlayzMC** [comment]
I use mcpe and I can't see the ride button up to the item bar
