### ISSUE TITLE
Support MCPE 1.1

### ISSUE THREAD

**Issue by caspervanneck** [BlueLightJapan/BlueLight#203]
can you make that

**Comment by ExaSonit** [comment]
https://github.com/BlueLightJapan/BlueLight/tree/1.1.0-Update
You can find it here

**Comment by caspervanneck** [comment]
@ExaSonit  its not working and know that

**Comment by ExaSonit** [comment]
use DevTools no?

**Comment by caspervanneck** [comment]
@ExaSonit  yes i us devtools

**Comment by BlawoHD** [comment]
#412
