### ISSUE TITLE
Corrupted Worlds??

### ISSUE THREAD

**Issue by linuzo** [BlueLightJapan/BlueLight#21]
Notice: Undefined property: pocketmine\nbt\tag\CompoundTag::$Entities in /home//Lobby/src/pocketmine/level/format/mcregion/McRegion.php on line 164
[20:58:47] [Server thread/CRITICAL]: Error: "Call to a member function getValue() on null" (EXCEPTION) in "/src/pocketmine/level/format/mcregion/McRegion" at line 164

Seems to give corrupted worlds error..

**Comment by kametan0730MC** [comment]
Does it occur at startup?

**Comment by linuzo** [comment]
No it happens while the server is running..

**Comment by erkam2002** [comment]
yes was me too

**Comment by MCPEGamerJPatGitHub** [comment]
Delete all worlds and set word generator from mcregion to anvil and load a world

**Comment by caspervanneck** [comment]
@MCPEGamerJPatGitHub  that not how you fix it if have lobby or worlds

**Comment by kametan0730MC** [comment]
fixed
