### ISSUE TITLE
fix where we can use enchantments with name?

### ISSUE THREAD

**Issue by XDqrkneZ** [BlueLightJapan/BlueLight#210]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP: 3.0.0
* Server OS: Ubuntu?
* Game version: 1.0.5 

### Crashdump, backtrace or other files

I can't make enchanted kits with AdvancedKits because BlueLight does not support enchant by names.. like mine_durability: 1... yeah BlueLight is almost perfect but need to fix this ;)
* ...

**Comment by XDqrkneZ** [comment]
no answer? ok

**Comment by haniokasai** [comment]
maybe it was fixed.

**Comment by caspervanneck** [comment]
@XDqrkneZ  fixt in #207
