### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by caspervanneck** [BlueLightJapan/BlueLight#3]
PocketMine-MP-DerivedVersion Crash Dump Sat Nov 12 11:54:07 GMT 2016

Error: Offset LightPopulated not found
File: /src/pocketmine/nbt/tag/CompoundTag
Line: 65
Type: error

Code:

Backtrace:
#0 /src/pocketmine/level/format/anvil/Chunk(120): pocketmine\nbt\tag\CompoundTag->offsetGet(string LightPopulated)
#1 /src/pocketmine/level/Level(2559): pocketmine\level\format\anvil\Chunk->isLightPopulated(boolean)
#2 /src/pocketmine/level/Level(2221): pocketmine\level\Level->loadChunk(integer 31, integer -7, boolean 1)
#3 /src/pocketmine/Player(3795): pocketmine\level\Level->getChunk(integer 31, integer -7, boolean 1)
#4 /src/pocketmine/entity/Entity(1569): pocketmine\Player->checkChunks(boolean)
#5 /src/pocketmine/entity/Entity(1507): pocketmine\entity\Entity->setPosition(pocketmine\level\Position Position(level=sg,x=500,y=74.2,z=-99))
#6 /src/pocketmine/entity/Entity(1628): pocketmine\entity\Entity->setPositionAndRotation(pocketmine\level\Position Position(level=sg,x=500,y=74.2,z=-99), double 23, double 0)
#7 /src/pocketmine/Player(3862): pocketmine\entity\Entity->teleport(pocketmine\level\Position Position(level=sg,x=500,y=74.2,z=-99), NULL , NULL )
#8 /src/pocketmine/Player(970): pocketmine\Player->teleport(pocketmine\math\Vector3 Vector3(x=500,y=74.2,z=-99))
#9 /src/pocketmine/Player(913): pocketmine\Player->doFirstSpawn(boolean)
#10 /src/pocketmine/Player(1772): pocketmine\Player->sendNextChunk(boolean)
#11 /src/pocketmine/Server(2411): pocketmine\Player->checkNetwork(boolean)
#12 /src/pocketmine/Server(2170): pocketmine\Server->tick(boolean)
#13 /src/pocketmine/Server(2051): pocketmine\Server->tickProcessor(boolean)
#14 /src/pocketmine/Server(1677): pocketmine\Server->start(boolean)
#15 /src/pocketmine/PocketMine(478): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Wesleyvanneck\Desktop\nethercube\, string C:\Users\Wesleyvanneck\Desktop\nethercube\, string C:\Users\Wesleyvanneck\Desktop\nethercube\plugins\)

PocketMine-MP version: 1.8dev #0 [Protocol 91; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT DELL-PC 10.0 build 14393 (Windows 10) AMD64
PHP Version: 7.0.12
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
aFloatingText 1.2 by AlexBrin for API(s) 1.10.0
AntiServerStop 1 by paetti for API(s) 1.0.0
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
ExternalIPChecker 1.0-Alpha by hm for API(s) 2.0.0
FactionsPro 1.6.3 by Tethered_ for API(s) 1.12.0
Genisys-DevTools 1 by PocketMine Team & iTX Technologies LLC for API(s) 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
MagicWE 0.2.5 by thebigsmileXD for API(s) 1.13.0, 2.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
AutoLapis 1 by  for API(s) 2.0.0
PlanB 1.3.0 by Gamecrafter for API(s) 1.10.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
WorldProtect 2.3.0 by aliuly for API(s) 1.10.0, 1.12.0, 2.0.0
EconomyPlus 0.1.5 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
LiveTexts 1.4Pre by EmreTr1, EmreTr1, caspervanneck for API(s) 2.0.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
PiggyAuth 2.0.1 by MCPEPIG for API(s) 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
SurvivalGamesV3 3.1.2 by ImagicalGamer for API(s) 2.0.0
SW_svile 0.6dev by svile for API(s) 2.0.0
GrabBag 2.3.0 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
MyPlot 1 by Array, Aericio, SalmonDE for API(s) 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWltv2zoS/iuCzsEiBXyR5FscoAXSXHqy66RC7TbBVgcBLdE2G0nUkpQd56D/fYeUL6QcN05i
9Cl5qMUhOfPNhTNDqf/YgiTYPnKbncNuy203OxU7RlycMUaZffSPLeYZTNtYjSt2gjlHY0n5PBpx
LKweGU+ET7M8RgJHVkqFNaJ5GsHaUR7H5ySWi0+OguArx4wHwTXmMZ5PUZri8C4ITjG/EzQLghSL
CWZhPsRBwFkYBBkN77BISAqEdCiCQKBxEJzQJJP8B2hcyyaZFFOIqMOm+npPHbbUYUdd2wCLY5iy
j9qtii0YCuHxu/2HY5X3xniK4/qIsgSJOkqnJK6fTPL07sD1nHdH1pPIqh+oss4nLA64YCQdl+z0
DqD84W6R25P/HnitVrckS00HQYErCBQwkCuRVT8Qboo4GFIaY5QqUd6vRXme+7goNV/9EFMUFQYg
qcBjzKyGW7GWz9VOxVoIs1wlrrEhzo/RHLODRqfb+qWkMRbPEdTcEIRTQcS8fqZ+DtxWu2zEAkn1
QziB+FOyuGGq1pMsnU6JZbEgCIoV1Q/geZ9yIghNDx5RdTlnrRapifd8XLl/33Kcyvx9p1nzKg/v
q93uOwWq/RSotne4O6jjNPpCBdoPvooV0XwYY8trrB4dBbqzNQoO294TaAWOcUaZ2Ae+q6+9nrX4
UcAOtwHrdpwt0fIoHjiFkyD4hkNBWcNa/B5s82F3q1S3sUVqRM8J46KfoVlqBKnrbGPmdjreFm4c
p9EVvl8cMIPdZirqYzYFdl7TdX91gK6wmFFW4uZt5eZuGLiYAQOTsMSlsZWL03J/wcVnNIQqRZnJ
rrmNndvudLaw4wKByw02m+nBV4+X8HgARXQLp9vbkKZQCvLQDCFZNOAgwqE5gbLLe5BoIdHR4Q8I
porBKRckhvJ5iUjao+OxtmpRYZ5ZY3/3vizOxySFxe/sv39WFg3FKxuMl1R+kF1AsY9GKOa4Yoc0
ko3A3289wVtP8NYTvPUEbz3BW0/w1hP87p6gYo9xihmKZVMA9uFwiKG4u7XDCE/BzMOcxJF95ED5
ZlTQkMLCrluxUUZgmVdzag6sGhMBI2fHP9jA0F1MhnJP7VBxyFMkX4jY1ySN6IxbVwPr9KzXq/on
lgsyLIXDcpuNbsM6WC5ynXfW8eVpuwkM5FuJI7sDgFwPhg9wwmDcWACE2VvKJf+Lq6sBENRgBu3I
qjHh0gLoHAqsAJsO4HRKwgKWSa+sLeVCZrFRLiaUcdnCHMf4/iM4RVpW2eg72FJqIAk4RRBegAui
DzqgCGeAkhdNEKcjcaoTEiSbpRVDaDJKGGQrAAv8z/3B9ecvvVMgzfAQ8rAEPBEiO6rXp3e1kCZ1
BExub4es0PcYMntxGvoQG5qWpQldTUPJDGEhiKHiazQ0pBbn6gn10jyOpSL9Lzp6GGmQVXDKUNCA
k39TPsnRX6eme7yXg19xDAJyeeKfBQHAgB5KZY+1Fv3B8ZfBV3/DRRx8BIdnkg+Vn1bc6lIZ0PDs
XmCWovjCP5E5HjNN3825inGCnepxnE2QaYFJoqnuvcZtG+KhZXgE0Q5uPEeh7B04lAtNPZ1qKtau
NUylBiq54eh2b27VhAfBYrB7XH7CKeFzXj3F0wFULK5ptTG19ZCti5k1wCix/mWRwQ08hpOUxnRM
MLd6vZN9eXOJR5aMFbJnBu/gRqKrb6gIFiFgSKG6Ms0WGlF3cKPmDk3/9k5vDM92VU5/lb7AEk7s
CsBOWecxpYFPVZ77uqYM6HuJxiS8PtOUXVJ0TSE/1VqmqhDIQzLmCdyxb0pZqvF6rRcgyto+4uBF
JF+idH5NWRxxQ5UV0cy3rkKoaYNiksfzfcVowU02++l8puQ/p1hc0eMIwArCoYT6umvKM6U0WnNN
pb4hMsUP7fbeks2SYRCUkJQIOxbFXNAe4NI9tqZtSzd7ctFK0HM8A9eY9KOGthibXmiUQ+sTrA0Z
GkHF2VuvlYHgobpWKfnPzQUaJO0qUvWL9rIuGMb1BHE1rURI3XOGfcwS3VtrWtkGHdMG7eb5ueNA
ZYDcIy8gF+mIpHBp33veuC0kgWmW0LTHF1hK7V2YZc0HzFH0gf8hQreHRiwZxDTH2ZTGfdDAVN99
udprwTtkzGXLPZvNahiQSKY1cSe1UslyUR80vQyymUkbT2bSRaRXlrmnsp/cqvJqVmDaVemScy9z
wkYEx5F2Na9mjxwCQ3/Z7MLFnCZzCAzd+zrVLJ5uuXheJLK+oVgeRLZxPamsrquNV/W9azzQ8Rrg
dsh1PUj18v6ma7immeHd9BkuRXjC8IDJerR+ChHPIE6LG/++Su0KElxlNHQ7KKhajAGOsU+ZKF4r
6B2QNlNObt5uEf/a5kE864rpk/F4DlVtoufnFa183Sx1CrIx9C8+7cspK7nPUaAfoywz7o1Liml/
D7rqUnn5QX9Q3JF/+9KAF6Jf3G37l8uqsVRCapizKZkWp55/a+ialmZKt4xyxG1LH69SuYQhCDZB
7eLF61s+Vd/d1sotSWZSbBfv7TS1ilX78qBkFgR8BopcJzveIj4xNPyIxvo1eEF5TdVz9fL3LHXg
es/FgKGUjwpHl3LEGNAN5YfEF4YpivEPlEaMAr+niuDSEjJ1Qh2heoOwIGzr2b/b1wTLtHx2f4+Y
nAdVjjEjIZGvTPooTmh6evY61y/r3bF/ATwXbS1N8VyzW4ETzLXE+2REyKbvZIJEqetVpFIRLMdE
0Yq+rMXVWuvHgkJ/4XSDp4Tm3D+rLun2ln5Ygl4/7aEbVmzkoSfj9Box/Q3timQaqVWuPE+2i684
L6V+dvP4cAA5A5C/5fysLPJTvslfra3NE+g9bJDEVRNfg542kxdpzAtyhhiYFDgsNIYOB6dc+RnM
fUIZ1j8nDEP5hVGnQJ0A6yBm0Bb/q2JFiJAwxiMSy/uqRpkgPileM8CAwFGb6rM/uHEKkpDNM6Ev
6Ps9fZiFJuwveBRjFb06lWPOyySBpDKRTkvm/H+x+oqyeLJaaqoKFcaqWp7jtpym04HHPy+iI8tr
ugg7TvewG7ndbms0CofDUbsRtTrdbrPRbrRGaNTtdjzrT+At6B1OyYNpiweSKWXhOMsvOg/FF6LV
NAzvlVPX5qWJrBuO03BdryvT0+lnfR48nnJubOmTJIvxzaVhthLbWRTdl6YZVu/zTeKMkZI3rzG6
Y3ikCnHR0IY5izeMSgzTw1jghtrTqRbVm6s45sbGYfGxT6fNkQK+vNZkYiJx8kV305YGmagIXX4K
gcN1G1GRYiOI/guBbH32QxROtOj5+fP/7d6t4A==
===END CRASH DUMP===

**Comment by haniokasai** [comment]
@caspervanneck try this bin.
https://bintray.com/pocketmine/PocketMine/Windows-PHP-Binaries

**Comment by caspervanneck** [comment]
ok @haniokasai

**Comment by caspervanneck** [comment]
fix thank you @haniokasai

**Comment by haniokasai** [comment]
ok
