### ISSUE TITLE
/helpコマンド時の表示

### ISSUE THREAD

**Issue by fuyutsuki** [BlueLightJapan/BlueLight#32]
![img_5151](https://cloud.githubusercontent.com/assets/16377174/21452403/053dbb38-c94a-11e6-80ed-aeab3eac7c1d.PNG)

写真のように一括表示されず、だんだんと追加されていくような表示になる

**Comment by erkam2002** [comment]
it's a client bug -.-

**Comment by erkam2002** [comment]
Close chat and open again

**Comment by fuyutsuki** [comment]
ok, thank u
