### ISSUE TITLE
Please support command_block

### ISSUE THREAD

**Issue by BeerMC** [BlueLightJapan/BlueLight#326]
Command block is one of MCPE new features,but  server doesn't support it by now.Can you figure it out?

**Comment by MalakasPlayzMC** [comment]
It is very easy to add command blocks but it is difficult to code the menu of them

**Comment by BeerMC** [comment]
I think the command block should be able to run the commands of plugin.
Handling the permission of commands in the block is also difficult.We know some plugin-developers just "return false" if a player doesn't have the permission,they may be lazy to add the permission in plugin.yml .How to deal with it?

**Comment by MalakasPlayzMC** [comment]
I can create a modified version of BlueLight with command blocks but I can't code the menu that it should open. You can download TapToDo to add commands to the command blocks

**Comment by ExaSonit** [comment]
Command block was added but you cannot use them in creative or survival or spectactor gamemode, and it cannot be destroy

**Comment by kametan0730MC** [comment]
Please from plugin
