### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by TheRoyalBlock** [BlueLightJapan/BlueLight#328]
My simple suggestion is to move all of your "ToDo" things to a project. Create a project here https://github.com/BlueLightJapan/BlueLight/projects/new with the title of ToDo. Then, make the tiles as ToDo, In Progress, Completed, and Long-Term-Project. Add subtiles as needed.

**Comment by ExaSonit** [comment]
file address doesn't exist

**Comment by TheRoyalBlock** [comment]
The link is only for members of the BlueLight team who have the permission to create a project. For you, just use https://github.com/BlueLightJapan/BlueLight/projects

**Comment by kametan0730MC** [comment]
Created, thanks for the suggestion

**Comment by TheRoyalBlock** [comment]
No problem! Don't forget the cards and subtopics!
