### ISSUE TITLE
Move Request

### ISSUE THREAD

**Issue by AppleDevelops** [BlueLightJapan/BlueLight#329]
Hello BlueLight Team, I've created a org to move all spoons of PM and Genisys, etc. and was wondering if you'd like to move BlueLight there. You'd get full access to all repos, meaning you'd be owner, and you'd extra support from the rest of them team.

**Comment by haniokasai** [comment]
my answer is yes,but we'll not delete this(Bluelight) repository and this org. if spoons of pmmp org was deleted,we are back to our org.

どう思う？ @kametan0730MC

**Comment by nightmare3832** [comment]
I dont want to do much

**Comment by kametan0730MC** [comment]
@haniokasai つまり、公式に作るが、公式が潰れたら戻るわけね、

**Comment by kametan0730MC** [comment]
We move to that, but we also use existing repositories in parallel

**Comment by kametan0730MC** [comment]
@AppleDevelops Is it okay?

**Comment by TDMidkwhatisxd** [comment]
he is from PMMP, he wanna delete all forks at once

**Comment by haniokasai** [comment]
@TDMidkwhatisxd lol

**Comment by TDMidkwhatisxd** [comment]
He just deleted his org ^^

**Comment by AppleDevelops** [comment]
I didn't delete the fork, ImagicalGamer deleted it.

**Comment by AppleDevelops** [comment]
And you're calling my a cyber bully? I made Tesseract, I updated it for a year, so you need to stop being stupid and understand that i nrver deleted it

**Comment by kametan0730MC** [comment]
I understood that.

**Comment by kametan0730MC** [comment]
Has the team been deleted? Thank you for calling out

**Comment by TDMidkwhatisxd** [comment]
apple, I talk about ppl, who spam in forks, not everything is about you ^^
