### ISSUE TITLE
Minecarts are crazy

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#330]
If you place a minecart somewhere,it is driving fast or slow alone.

**Comment by poustmal** [comment]
![screenshot_2017-04-20-13-32-58](https://cloud.githubusercontent.com/assets/22281205/25247911/f78c3212-2614-11e7-891c-ebb4e50eb0e0.png)

**Comment by TheRoyalBlock** [comment]
XD

**Comment by BlawoHD** [comment]
😂

**Comment by nightmare3832** [comment]
Please try again

**Comment by poustmal** [comment]
nightmare3832,now minecart works normal on rail,but when it is on ground,it seems that it can't stop,goes slowly idk

**Comment by poustmal** [comment]
![screenshot_2017-04-21-19-35-32](https://cloud.githubusercontent.com/assets/22281205/25287470/22a33ad0-26ca-11e7-8a00-b3553e8ad9ac.png)

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other

**Comment by TheRoyalBlock** [comment]
Yeah, we realized.

**Comment by ExaSonit** [comment]
Can you close all your issue poustmal? Thanks.
