### ISSUE TITLE
Some 1.0 items are missing

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#332]
Can you add splash potions and end stone brick in inventory and can you add also lingering potions and endercrystals from clearsky?

**Comment by ExaSonit** [comment]
You know that 1.0 is in beta?

**Comment by poustmal** [comment]
Not 1.1.0,for 1.0.6 that is stable

**Comment by ExaSonit** [comment]
If you try to use creative inventory of pocketmine it's the same thing

**Comment by BlawoHD** [comment]
i added today

**Comment by BlawoHD** [comment]
Was added
