### ISSUE TITLE
Join issue.

### ISSUE THREAD

**Issue by MCPEGamerJPatGitHub** [BlueLightJapan/BlueLight#335]
### Issue description
Cannot join server with latest build.
Shows no errors in console.
### Steps to reproduce the issue

1... Run BlueLight with the latest build

2... Start server. 

3... Try to join with client. It will not work. By the way, it is not a Win10 issue.

### OS and versions

* PHP: 7.0.3
* Server OS: bbe46ee
* Game version: 1.0.7

### Crashdump, backtrace or other files

* ...

**Comment by BlawoHD** [comment]
Fixed
