### ISSUE TITLE
accepted protocols dont work

### ISSUE THREAD

**Issue by Driesboy** [BlueLightJapan/BlueLight#341]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP: 7.0.18
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by BlawoHD** [comment]
What does not work?

**Comment by Driesboy** [comment]
accept setted 1.0.6 to the accepted protocols
and 1.0.6 players cant join and got a client outdate

**Comment by ExaSonit** [comment]
There is a plugin to allow player to join in your server with another version

**Comment by Driesboy** [comment]
what plugin???

**Comment by Driesboy** [comment]
?????

**Comment by Driesboy** [comment]
@ExaSonit

**Comment by ExaSonit** [comment]
some plugin on old or new pocketmine forum

**Comment by Driesboy** [comment]
nope
