### ISSUE TITLE
Bugged command block

### ISSUE THREAD

**Issue by ExaSonit** [BlueLightJapan/BlueLight#342]
Command block can be place, but op cannot destroy it on creative gamemode and he cannot open it to put some command. It can be destroy only with tnt. P.S. add title please (or it's already added? o.O)

**Comment by BlawoHD** [comment]
@ExaSonit 
You can only place command blocks that do not use.
Title has already been added.

**Comment by ExaSonit** [comment]
Wait a moment, how i can send a title? o.O

**Comment by BlawoHD** [comment]
Command or sendTitle?

**Comment by ExaSonit** [comment]
sendTitle

**Comment by ExaSonit** [comment]
Also command

**Comment by kametan0730MC** [comment]
$player->sendTitle("String");

**Comment by kametan0730MC** [comment]
I create title command

**Comment by ExaSonit** [comment]
In that php file?

**Comment by ExaSonit** [comment]
So i can use path in a plugin

**Comment by kametan0730MC** [comment]
I added title Command

**Comment by kametan0730MC** [comment]
src/pocketmine/command/default/TitleCommand.php

**Comment by ExaSonit** [comment]
title was add in branch: master?

**Comment by BlawoHD** [comment]
yes

**Comment by ExaSonit** [comment]
$player->sendTitle("args");
and for a subtitle is: $player->sendSubTitle("args"); ?

**Comment by ExaSonit** [comment]
Thank you, now i have made a fantastic join plugin with the titles :)
