### ISSUE TITLE
join issue persists 

### ISSUE THREAD

**Issue by MCPEGamerJPatGitHub** [BlueLightJapan/BlueLight#345]
### Issue description
Same as #335
it is not fixed.
### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by ExaSonit** [comment]
Are you sure that you have installed latest version of Minecraft:PE or you had install a beta of 1.0.7?

**Comment by MCPEGamerJPatGitHub** [comment]
@ExaSonit yes. Used the latest stable build on Jenkins & Updated Client version.

**Comment by Driesboy** [comment]
it works for me btw
