### ISSUE TITLE
add timeban and timeipban and timecuid ban

### ISSUE THREAD

**Issue by Driesboy** [BlueLightJapan/BlueLight#346]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by ExaSonit** [comment]
You can download some plugin to do this like BanSystem

**Comment by MCPEGamerJPatGitHub** [comment]
@Driesboy That should be handled by a plugin

**Comment by ExaSonit** [comment]
You can also download a my plugin for ban player's ID on my official repository: https://github.com/ExaSonit/BanID
