### ISSUE TITLE
strange messages on console

### ISSUE THREAD

**Issue by ExaSonit** [BlueLightJapan/BlueLight#347]
This appear when I place a sign why?

pocketmine\nbt\tag\CompoundTag{
pocketmine\nbt\tag\StringTag:Bug
pocketmine\nbt\tag\StringTag:
pocketmine\nbt\tag\StringTag:
pocketmine\nbt\tag\StringTag:
pocketmine\nbt\tag\StringTag:Sign
pocketmine\nbt\tag\ByteTag:1
pocketmine\nbt\tag\IntTag:244
pocketmine\nbt\tag\IntTag:71
pocketmine\nbt\tag\IntTag:197
}

Image below

![issue](https://cloud.githubusercontent.com/assets/20334614/25305538/5afd6a14-277d-11e7-9ca6-86660d0589bb.JPG)

**Comment by BlawoHD** [comment]
What is that,

**Comment by ExaSonit** [comment]
I don't know, it appear when I write a text on a sign

**Comment by BlawoHD** [comment]
When I do this happens nothing

**Comment by ExaSonit** [comment]
mmmmmm.... maybe is for a plugin that use nbt tags 🤔

**Comment by kametan0730MC** [comment]
Thank you for your report.
