### ISSUE TITLE
Undefined property:  McRegion line 164

### ISSUE THREAD

**Issue by linuzo** [BlueLightJapan/BlueLight#35]
Notice: Undefined property: pocketmine\nbt\tag\CompoundTag::$Entities in /home/kidzzone/Lobby/src/pocketmine/level/format/mcregion/McRegion.php on line 164

Get this while server is running,

**Comment by haniokasai** [comment]
@kametan0730MC

**Comment by kametan0730MC** [comment]
Fixed

**Comment by kametan0730MC** [comment]
Thank you for your report
