### ISSUE TITLE
Noteblock doesn't work

### ISSUE THREAD

**Issue by SuperXingKong** [BlueLightJapan/BlueLight#354]
### Issue description
Write a short description about the issue
When I clicked on a noteblock, it didn't make any sounds.

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP: 7.0.18
* Server OS: Linux x64
* Game version: v1.0.7 Alpha

### Crashdump, backtrace or other files

* ...

**Comment by poustmal** [comment]
Someone should add resource packs from pmmp if its possible because there aren't any sounds now.

**Comment by kametan0730MC** [comment]
ok

**Comment by kametan0730MC** [comment]
Fixed, thank you for your report !

**Comment by poustmal** [comment]
Sorry,well,noteblocks don't working but on 0.16 here, were fine,but don't work again,reopen issue

**Comment by poustmal** [comment]
sry forget one comment I wrote.deleted.

**Comment by SuperXingKong** [comment]
Thank you @kametan0730MC . I will solve some problem if I can and create a pull request😄
