### ISSUE TITLE
Question - urgent

### ISSUE THREAD

**Issue by ExaSonit** [BlueLightJapan/BlueLight#355]
How can i send a title to a determinate player?
P.S. Bottle of enchanting are bugged
![screenshot_2017-04-23-13-39-28](https://cloud.githubusercontent.com/assets/20334614/25313192/64a2d8f8-282a-11e7-9900-b52d476e9f9a.png)
![screenshot_2017-04-23-13-39-21](https://cloud.githubusercontent.com/assets/20334614/25313193/64aa75b8-282a-11e7-9cba-63fbee1c2e8a.png)

**Comment by kametan0730MC** [comment]
$player->sendTitle(Title, subTitle)

**Comment by ExaSonit** [comment]
No... In game i mean

**Comment by kametan0730MC** [comment]
You can not send it to a specific person

**Comment by kametan0730MC** [comment]
You can do it with a command if everyone is OK

**Comment by ExaSonit** [comment]
On normal world i can do it... Please add this feature

**Comment by kametan0730MC** [comment]
Was it so, I will implement it

**Comment by ExaSonit** [comment]
Like command: /title <target> <title> <subtitle>

**Comment by ExaSonit** [comment]
What a fuck...?

**Comment by ExaSonit** [comment]
Ok thanks

**Comment by kametan0730MC** [comment]
You can /title player title subtitle

**Comment by ExaSonit** [comment]
You have added it?

**Comment by kametan0730MC** [comment]
Yes,

**Comment by ExaSonit** [comment]
You are a genius!
