### ISSUE TITLE
Bug with arrow

### ISSUE THREAD

**Issue by ExaSonit** [BlueLightJapan/BlueLight#357]
I find a bug with arrow

**Comment by kametan0730MC** [comment]
I cant open this zipfile

**Comment by caspervanneck** [comment]
my breowser says its virus

**Comment by caspervanneck** [comment]
@kametan0730MC

**Comment by ExaSonit** [comment]
It isn't a virus but GitHub don't allow me to upload file in format: .mp4

**Comment by ExaSonit** [comment]
![screenshot_2017-04-24-13-29-45](https://cloud.githubusercontent.com/assets/20334614/25335170/206c688e-28f2-11e7-9406-650638a369c7.png)
I have made a screenshot

**Comment by kametan0730MC** [comment]
OK

**Comment by Driesboy** [comment]
https://github.com/pmmp/PocketMine-MP/commit/ee2798611effa945cc592158b64364d1698a8dbe

**Comment by kametan0730MC** [comment]
thank you

**Comment by Driesboy** [comment]
https://github.com/pmmp/PocketMine-MP/commit/caf49372224632506a883905d718c07d37c520a1

**Comment by kametan0730MC** [comment]
Fixed,thank you for your report

**Comment by Driesboy** [comment]
np
