### ISSUE TITLE
Villaggers 

### ISSUE THREAD

**Issue by ExaSonit** [BlueLightJapan/BlueLight#359]
If the villagger is spawned with the villagger egg, all spawned are the same and they don't move, they don't suffer damage from fallen and after two hits with any sword, if I hit them more, they don't 
die, as if they have god mode
![screenshot_2017-04-23-23-37-15](https://cloud.githubusercontent.com/assets/20334614/25323603/b13201f8-28c0-11e7-9f52-fca3ea168d73.png)

**Comment by kametan0730MC** [comment]
Villagers will not move without AIPlugin

**Comment by ExaSonit** [comment]
How i can find it?

**Comment by MCPEGamerJPatGitHub** [comment]
https://github.com:EssentialsX

**Comment by kametan0730MC** [comment]
Sorry,I don't know

**Comment by kametan0730MC** [comment]
It might be implemented next
