### ISSUE TITLE
Undefined class constant 'EVENT_SOUND_BUTTON_CLICK'

### ISSUE THREAD

**Issue by linuzo** [BlueLightJapan/BlueLight#36]
Undefined class constant 'EVENT_SOUND_BUTTON_CLICK'" (EXCEPTION) in "/src/pocketmine/level/sound/ButtonClickSound" at line 29

Perhaps some packets need to be updated for this to work??

**Comment by caspervanneck** [comment]
nope its a plugin its a skywars plugin
@linuzo

**Comment by caspervanneck** [comment]
if you use this https://github.com/svilex/SkyWars-PocketMine you get this eror

**Comment by linuzo** [comment]
Yeah, we do use that..  but why does it give that error what changed?

**Comment by caspervanneck** [comment]
that sound isnt inplmentit

**Comment by caspervanneck** [comment]
sorr for my bad eng

**Comment by erkam2002** [comment]
I thing this sound is already implemented ..

**Comment by linuzo** [comment]
$p->getLevel()->addSound((new \pocketmine\level\sound\ButtonClickSound($p)), [$p]);

Did the packet for EVENT_SOUND_BUTTON_CLICK change and perhaps isn't updated yet??

**Comment by linuzo** [comment]
Ok I fixed it..  

Someone add 
const EVENT_SOUND_BUTTON_CLICK = 3500;

to 
pocketmine/network/protocol/LevelEventPacket.php

then it will work 

thanks

**Comment by linuzo** [comment]
https://github.com/linuzo/BlueLight/commit/ce74b66c2c14e181cdd2bbed5590428902e9d825

**Comment by haniokasai** [comment]
done?
