### ISSUE TITLE
Idk what this mean but server crashed.

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#360]
PocketMine-MP-DerivedVersion Crash Dump Mon Apr 24 05:26:21 CST 2017

Error: unpack(): Type f: not enough input, need 4, have 0
File: /src/pocketmine/utils/Binary
Line: 258
Type: E_WARNING

Code:
[249] 		}
[250] 	}
[251] 
[252] 	public static function writeFloat($value){
[253] 		return ENDIANNESS === self::BIG_ENDIAN ? pack("f", $value) : strrev(pack("f", $value));
[254] 	}
[255] 
[256] 	public static function readLFloat($str, int $accuracy = -1){
[257] 		self::checkLength($str, 4);
[258] 		$value = ENDIANNESS === self::BIG_ENDIAN ? unpack("f", strrev($str))[1] : unpack("f", $str)[1];
[259] 		if($accuracy > -1){
[260] 			return round($value, $accuracy);
[261] 		}else{
[262] 			return $value;
[263] 		}
[264] 	}
[265] 
[266] 	public static function writeLFloat($value){
[267] 		return ENDIANNESS === self::BIG_ENDIAN ? strrev(pack("f", $value)) : pack("f", $value);
[268] 	}

Backtrace:

PocketMine-MP version: 2.0dev #0 [Protocol 107; API 3.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.5 #1 SMP PREEMPT Tue Dec 3 15:37:57 CST 2013 armv7l
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Loaded plugins:
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
PurePerms 1.4.0-INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
SW_svile 0.6dev by svile for API(s) 1.13.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
TimeCommander 2.1 by LDX for API(s) 1.0.0, 2.0.0
MagicWE 0.3.0 by XenialDan for API(s) 2.0.0, 3.0.0
Slapper 1.3.3 by jojoe77777 for API(s) 3.0.0-ALPHA4
KillRate 2.1.1 by aliuly for API(s) 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNW2tz20ay/StTdGrXvkVQfEiixJT2llaSva6Vba2krLMVplxDYEDCAjAIBhDFpPzf7+meATCk
FCdr+8N1PoiYR0+/+0wD+a1XJZnqzUb7x+Pjo/H0aNTvqbLUZW/2W6/aFJjqXXx4f3r99vXbV71+
L1PGyCWN1nkhw7vnL2biFstEPBO5roTKdb1ciSQv6qovcqUisd8XK3mvxBDb4ySlvXumDPcKHd6p
KktytVdXSWr2/p7kstxgVYqx3mx8cPSp3yvSepnkvVksU6P6vVBHilgb7x+DzryaV5+wYXww5Cf7
e4Tf/GPMg0W9SJNQmEpW+BPXeVglOhfrMqnUy1TL6vl39zKt1YvfeNPE0S1VVZe5uHh7/vr07duL
mxtxcnIijErj2ezvr199sBPifwWrYd6L572+cJTEDMeVpbp//sTki+/5nH2P44OG48PPcVwqGV06
jkG+Dy1X4jsZhnUpw404EcHIyTB1Mlhuw5UK7y5VvqxWbuO+4+HIrbOcgcIfS+vM7kRyUhLVFy9+
Gv0MwbcX8Awm7HmNzZL4ecf331q+D4duvtV+qes8cvbpd7Ja9g9HjQso+IalMN6lYPfa9RPfZQ49
Axw2Bjg8/EOXuXzsM4fT/9ZnPuMdUOETw1aAI8cy4qKCHhAJP/3c7y1VrkqZUljcq9KAUywbD4aR
useuRZ2kUW82RCiVutKhxsLRcNrvySLBuslgOKDIXCYVnoZ/8h82lPIuTRa0Z3DEFOpcUibpXSZ5
/SBSHcp0pU0lJoP9wYF4NhI3b67E1fXFxZurW3ELdztXoZiI0cFsMp0dTMXZza0YD0cTIcvsfpqC
YrEqQG8KDid4+lXlkccwJj9o05yHAX6QeVTqJOq1mcOQWl5KNqC5KjU9Okb90b6nutFgMhhjRNbV
Spcg8FPvVlUrVaroQ+9np7ifsGwEJdOAyuUiVWCuKuGmvUgVYNVY4xgdV+f+QCYpnfmHz+fu4Q1N
If1pSYJevbu5ff/u+vIcQ2u1MPC93iyv0xSynaVKlpdyufTE6ca2hRmxujxhLhU8JnoXvzm7utiS
Z/jl4rSHz+eXYF+VfyBHb1VVhZnt7cHvVvViEOpsz+drr5MG4l7VpbpSZWY8cbuxbXH3B8Pg9dvz
i39vC324//LlcCj+IqDwjyqsXudxkifVZtugE9bV+Gs08cGeNJ+3DHo/v0ArvNe68l5HB0q5MEbl
VYK6CDN2etka7m9nhKc9wViVi1slM08dY+c5X6UNn5tv5RpbEkIRN+8/mHsGFq0S2iFfAcPBoU2J
ngbsqkc+8IXSMrX53Kzn85v32VY039yeXt/+cPVELN+oEjyegidfgG5w24ajybYAF/c6vQE72zKM
vlyG7mQI4XPx+4KwxWCw9Xo9UOCHSA+qO7LNrSxu9bmfdZuRbbEg2LZcL2V6962SUyWLSkfIs93Z
fyLH/ltX6lqtZRl53HuDvgBUlHZKxuX5j4+LxVdGE2jO5x0L8/mfqBiNce6xreRtgyws1ADiQMgE
6bBCOrSA3wnpDW4LOVp8XsbjbyRix8CfF3E3Y5z/GHC28IQhf8Rt50xnGXCC8kXeHvekhmN+VuTh
NxJ5i4Gvl3pbHgj+Ri6T8L1fKJqR7RQ52a0RP6ocqfZc5lulwYo9+Rqx3fm7sn4mUaayKLas1ozs
oredHPlRf9RqSv88GZj34PTy6h+n+1+c7+35X2yujrG9RhTI+c8kTa9l5dezdminGOxmTZkmdbp5
ZKn/SrzeFV/M3+hc0WX8jTQmuVcXoc51RgPu1+nVazy80ml0U1EyvJb53Q9Fr1OO5WU+vwPvJXj/
Yi3JVH1kXA+CXtcgcAB/D9cutZdJg/y21yrKocazlax2QCMPPcKMT6HFL8OGHjJ9rNvtO8eP6j7R
NWBM0Iz3fgdIEtPdr28AI5nMJ7omyRK6ge4aZ+CaP8BlEe5YJYpuVc+u2idxpoGcl4I6OfNynj+D
n4jTohTjfTHcn42PZqNxc5Wb0gJLLyADnPxHkzPgqFfX3lShy+pkdDyaTGhwiYWZjtTJkJ4y+QA7
yw32nIx4xBRynQeFTepQ2UkwouH1CqKnialOdBzTgLVP8Eutys2Jzr2hEg7sRiJlwjIpmI4FOyID
RBW1SfKlcIFAvoarK1xQvEIyNBsjcPlk4TJdRSfzejiU09T+if+j7Y/wn1ZU+7R4Zf8eX9u/0pOf
2mwnuS4zmTJNiF9ugjTJEqhlON5/Q6Mp/Duoiwi+3Ugo81zXeaicggIZrhJ1rzKAY+Pku0/UOoig
FYl1J6xfmaZ6HcRpsly1urI6lXkCFpqtdizTi2ZgBegQ6rI9vrgvGi0mcZyEdVptTsZsQm5IoOIG
RlUVNGlOWAQwlz5yhGE3ZZSKvJWsl5eXp7c0REYbFMhFa11GJ//D/yBMXenAyHvlOGEvCHw3iHUJ
DbVO5UZ1Tj3GoPMzZ4qkOBkO+D8apC5Dm24GmyylUBCUxUTIUVBDSmoMUTAInLTtMQgOcbtSRolG
DUKWSlQrJZBbDX7ISoRkxUoslEjyMK0jFeGHeBSEROtGZ9gZE4FdmkbGqi80NSkMkRSLUsk7sdF1
6WiJJBYQN4kTPgGGLBE/yM8g/FatW3J7kYolTGnEWud/rQRVJVkKUnRG3TC4zwbsg4nEWLnXK5WL
uliWMgKBwTwnbVpis3kunt2ukJ+DFEPgIpX5spZLJaiRyypzmjcJnrlplPzKSqWtZ9S5tFJsbwQD
TY5T+WCd3CWFihI50OVyj572LuECH3T84fXNuw+Hk+Ng/IH2QY0toZmYI4cv5z066P2KGzyi0uAH
cQ4pqUfH+q1KmaPQV9AbT7M2mVPwgV+qYpPiapmESqyQJlI2cgbC1vu6I7mLjXGzqqtIU3zZfjox
4/JPmGqDo0gzSNMiLKVZqWjwOm5+9j9qeIiMSZ3HwegALMEbIzOwopxSfAsKAUphrkaK+0SKf1Eq
xBJOiU31nAmqX7TxZoV9kjzbaEjgOLPmlY4QEiMcF7UOzsMaAQrAStTNiHTbTQQQZQFBOvIXnHwb
OpRMKZkIuDi8iFhdbITzPSx3qbqd7VT37D0yBxwAbiijSJTKWG8lNuGfd2BHkuYoDQr46EKRPqBO
9UstUzLhEnAmF7bl/dwdiXL1AsTteSgRiopSAA9YLlU5wyyd/LbOFlA6QvDUbPLwVpo7REl5h6Ab
0PwPZDjy6UZIWrUqAZdquBFWmz6tTyPhMiTcvA81ZNCaITDCakEZp7GszhFttIRp37CbQR4EZKkf
kKlR7jYkDodH3rJGWrXswGUM7dIcvX2RVH+F5qqSd0WK6id77s5e8RwSwM5iTBphGQIn5YwpUYTb
IsXx/SrVCyiWgI6ww4JrF+WxTC3lYlOBIXFjWRny4Ykh89rsAJnWCTPGyhZUnlwNdEOG9RIncBek
NtSGnEnFyCvNidb8K6rc5LRLDTk0hRPpDOcsmUlbVGdiOOf0wpm8WtF7lf/n7BMk/AzzVJq/inlT
6YLPd+mt5cdRM5SMqPqqqOGGztxhCaA30Vy/KBANncbvnhrW2mAbuZxFDsYrArog2DDjvK9zZC+E
J5RGqeH3dGp1iaKfckmgQLfL5lyhiQZCrwtjm4vohHeUP6gk8vLB48Uks4P40F+hQqqchnVCvFoF
272tAFCjKkwn5mTY5OYXTzLkpJ5YqZeyXMD4QaiBjBjaUng9qVX2JWLF7RFujyb4mtdco30ugF9q
OMKLfpMQdjzBuYJNqnHcJIasc7GBeGcLJD/BHVa6TqOWkQTpY52LjnVyWlEw5xDwcDi0MopnLzkM
HiVG9hW7uxUqLnXW5Ffa6+YDPyV5NoUQznS7rvCE/3j76IoRrur8zlh9v5HIrnWGykK9E9GgZ5JG
WKRtw6M7gnzF0eX4EEwuIEBUI2fuO/bOtZ3YtRolfkJUlgItbfzD0nHLvoGoXHyCEBcFZYV1LtAc
RBNtxf4sqXmeq4pM0EI8eERqq99CVriJEPiQhIYNvagWLhNx3FkA62ZtAlqotg6yCp/5KauZoXgv
NxXR7otg5Pkw1Ts+NqgaVpBNDg5tMunqK18sqLhF1oYE9hh70F4MOp4G4h+4HkG9J8DM8Nezqx/6
2AsOFkg76ySqVjZTc1i35AMmPxNTBwY6mGBYMd7SgTiNEEYrmcZ7uAxY5BIpuJc7CEcKuuOThb04
bCuyR8vDRhcPFHMEfWTat/FMB79PcqBNiAW3URxrVN9/uMqvGnTQYXsCPrSJG8wE7PMicI8+DqO7
86JeWvNrlyoFVYiSHVo9qLC2AIdyDr28HbSzhjyCcQsu0oMkT4iNEcvWrLCx+F6WOaVpbyddd1xi
JiqOQF9EKBckTLcyk4jMDCatSIllndOnLhTGMd21KaRBucnxdBxkzIMkDtxYFwkNeIUN9Jr8RT2E
qrCnWHzcnRrLBKpnp+arttCLCvajXexLAF5YwcwzH234I+HGdqal1heLumI5QkkWk0195qsA8+yh
PPuJDBaRHHReE1mlTAwfiPpEHhV3ghAgaWRhejwTtGOeb+Ggv4kRwUiHGei+wE7Q3BXYrCSHu0PM
XcDN2LZOiUbs0XcVNdLC3jK0AURt6u4mMs9tmp3ZK6DGNYK03FzQVHOR4FQcyQpakff26km/2n4I
TbVEJayPNKdkNWvU5vTl0BujYoQUQwpT0JdLBDFyHaZJIXgnAuhNa4tM3zd3DFMrSmNICoau6Atc
Du/IMZJwxe5KF/wNbGSv8yl7ZcqbnePZnkxD0bJpPPfrmCUXNvYEe8c3ViV8V3SNsvZMpkOK8dj+
ZtySN0lmwcsJTR9n6/qvmnudsA5vGx+81GX/2rh7Zgh6FRcAtyWwW3DxyO+TlO+3W9kqxH0bldQR
4yzKSAxKoaxJkQdU6ZATVXALyMghqHVE4w6FNX6yNdwAXHv/u6FyRf69kEZ5hz0foVA8cUpfjDEx
empCVeHgBRcto3wuOFBuiTK1IBqDKhRmex65p1UVN3u6LhAVQk43dGMgM8l0LTfG0nZ0PEPZgu/K
X5PEnTJdjrEdyV0Y1G9WbbUWn+xZ8SX0NNNIvHy5ZIxFJZezVSMbaYWYpNs3NUPxE4iRtl4zfvK2
st/wN4XYv1CW1ELFlFa5XUkZjexjaVM64CZmA8RYuTf0LSIn0oR6TYr6EMXG9dUcQGvBPVfPmF8t
NFjB1fa4TnmZNlW6CdyXYoyvuCSU1MyqmPlGUNu2scjayExxLFP+I9TVINC2XfIEfGhYJimdRuxw
7hpvDTSw6FP9gkD3UKMdJv02JgfSFXLXPrBfyCis87ot0+wPn7SN5E/1uFHEeRkWcludd1sTkGG5
9ex62Z1PipC++LH+St2rThWvz/kgl6goPZH72DKOAAS0yYQTS9gq1sBa3uKLLJ4FiMlnYon6aTql
dO2YRi+Dx4pxtW0tE+6sQbsWccAR3X5OXDweGHjWTBx9EbVCF3XqqLnfBC53CM9zzipBYQulbd4H
7PB056ALF7yTSn7Zjo5cgqMqORP2Vtb4H7Sf18VMHNurmo0cTn8WizlaoDIdchWwbwtA9MBiJzqo
HeQxmS0ShKhd4pr1trM2s+mUmoCEZIQdtf7sHNCG2i4UI2cPqJW7PdJWnK1RYEMCWZ2L0feIMwee
vM4+rjLMX67zTUb3cw5nA/2allFqOLhp0U0zwwxB5HJZqqVr6bXNUrrl0Zead09LY/khcuYpfkhf
NkzYxLu74RN2dtaCVwe8OujAo7rwEssZvR3gdrVKdUFlHSgTmJQ7zlVzmQIQilWJ62xA6T4nDEeL
HA60r8ekT0S496kePqxxZTSVrRdNZnbUyEJ2uqFvdpRC3xI9oZI0QcG0Vrl4kARM7AOBUdB3TMwa
bngKzk79rZn4idEhymSfG14/E0Wbshuk4r9XYSGoCVfSqwnutjTvtRhxP1XyGDJyHTZ8e2PUDxiT
gFEHUjzW+VRmgH8Jev9FobvPT+1pM0EvwWbj76f9g+OHUX/yMOmPvx99HwFL2Kz1nF6Bh5RhTo6G
NrnZp/2DF/waSz1UwIj8gnn2W+8MBdP7sDbibw3axyLcmjW/pEmlJvxxyDSwH9D9ar/8bZYsQgCy
lTdA70bySJb+kPufCdrnuky9xzhJK+Wvjyv/299l5D9k/tQKwcwv8ent/Eez9UY/W9iXON7yLCw3
ReUN3FxdbgmfVz5fBG8i/gSsW6JN8uA/u56Y/UJqcEDfQqjYNXZ8UqtM+4wb9m7j87aBsvkjZ/dL
HGBmNCati4DeqB8M94dT/PzuNRwlPjhWi+nhNFajqTw8nB4fHB0vDsLh9DA6juXRUTSJ9lHDh+I7
0L5asTnG7kO1St+pHKXEV/l7YHmEvfsMiFZtJL/z5G8ers+mZPmksB8V268hmM+kpfHp0/8BuJYc
QQ==
===END CRASH DUMP===

**Comment by kametan0730MC** [comment]
When will it occur?

**Comment by TDMidkwhatisxd** [comment]
PocketMine-MP version: 2.0dev #0 [Protocol 107; API 3.0.0]
is pmmp  -.-

**Comment by poustmal** [comment]
I dont have this crash now,but if happens again i ll reopen issue
