### ISSUE TITLE
Regen is not the same

### ISSUE THREAD

**Issue by Driesboy** [BlueLightJapan/BlueLight#361]
### Issue description
Write a short description about the issue

Regen is not the same like pocketmine
so my anticheat gives me false positives

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by caspervanneck** [comment]
@Driesboy ik denk dat er wat spell fouten in ziten

**Comment by kametan0730MC** [comment]
What is Rigen?

**Comment by Driesboy** [comment]
Regenation

Op 25-apr.-2017 13:38 schreef "KAMETAN0730" <notifications@github.com>:

**Comment by ExaSonit** [comment]
Regeneration you mean?

**Comment by caspervanneck** [comment]
@ExaSonit  yes that is wat he mean

**Comment by ExaSonit** [comment]
If that is the case, there aren't even splashable potion...

**Comment by ExaSonit** [comment]
Emh... I checked now, there is regeneration potion in creative inventory .-.

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
