### ISSUE TITLE
Spam error when creating a sign is not fixed

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#362]
pocketmine\nbt\tag\CompoundTag{
pocketmine\nbt\tag\StringTag:loll
pocketmine\nbt\tag\StringTag:
pocketmine\nbt\tag\StringTag:
pocketmine\nbt\tag\StringTag:
pocketmine\nbt\tag\StringTag:Sign
pocketmine\nbt\tag\ByteTag:1
pocketmine\nbt\tag\IntTag:198
pocketmine\nbt\tag\IntTag:5
pocketmine\nbt\tag\IntTag:32

**Comment by poustmal** [comment]
and i updated bluelight now for updates.

**Comment by kametan0730MC** [comment]
Sorry. I fixed.Thank you for your report!
