### ISSUE TITLE
xp bar only change when you switch between slots

### ISSUE THREAD

**Issue by Driesboy** [BlueLightJapan/BlueLight#365]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1... switch the xp with a plugin

2... than switch the bar

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by ExaSonit** [comment]
If you try to open an anvil, the item that you have in your hand changes in another item, i think that is the same problem. This problem was cause by command block with mcpe's 1.0.7 update

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
