### ISSUE TITLE
Server says disconnected from server when crashing instead of <<server closed>>

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#366]

**Comment by poustmal** [comment]
It wasn't happening on other softwares.

**Comment by ExaSonit** [comment]
it's normal, <<server closed>> is a part of raklib interface (I think - I am not developer) so it's normal that you were disconnect from server. raklib is essentials for running the server

**Comment by MalakasPlayzMC** [comment]
You may have not so good connection to the server. You can modify BlueLight's Lang files to make it say Server Closed, and you can make it a phar file by using pmt.mcpe.fun. You have to press the Use the PocketMine-MP.phar stub to make it work

**Comment by haniokasai** [comment]
@MalakasPlayzMC oh, pocket mine tool came back!

**Comment by poustmal** [comment]
Weird,now server sent me server closed message when crashed.

**Comment by ExaSonit** [comment]
I think that crash is caused by a plugin (check the crashdumps folder) or it's depend from your Internet connection

**Comment by MalakasPlayzMC** [comment]
Please close
