### ISSUE TITLE
Add support for the ZMusicBox plugin

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BlueLightJapan/BlueLight#367]
The api3/network branch of pmmp works with it

**Comment by ExaSonit** [comment]
Hey, don't post request for plugin, it's wrote in bluelight's description!

**Comment by kametan0730MC** [comment]
I fixed plugin ,please use https://github.com/BlueLightJapan/ZMusicBox

**Comment by haniokasai** [comment]
lol

**Comment by haniokasai** [comment]
it is kind of @kametan0730MC  to do something request! but we dont accept plugin request.

**Comment by ExaSonit** [comment]
@haniokasai I saw it .-.

**Comment by MalakasPlayzMC** [comment]
Thank you very much

**Comment by poustmal** [comment]
I ll fix again music tempo,because I made it a bit more fast.
