### ISSUE TITLE
Turn off auto reporting in configs

### ISSUE THREAD

**Issue by AppleDevelops** [BlueLightJapan/BlueLight#368]
Could you please turn off auto reporting in the config or better yet remove it? You're blowing up the pocketmine crash reports.

**Comment by ExaSonit** [comment]
..... Unsubscribe to this repository by clicking Unwatch... Simple..
![img_20170428_173423](https://cloud.githubusercontent.com/assets/20334614/25535907/f7613b6e-2c38-11e7-8e20-8cb0f6e2357e.png)

**Comment by AppleDevelops** [comment]
Talking about this genius https://github.com/BlueLightJapan/BlueLight/blob/master/src/pocketmine/resources/pocketmine.yml#L160

**Comment by haniokasai** [comment]
@ExaSonit No, that's not the way.

**Comment by kametan0730MC** [comment]
Sorry

**Comment by ExaSonit** [comment]
xD

**Comment by ExaSonit** [comment]
What way? xD

**Comment by kametan0730MC** [comment]
I changed to bluelig.ht/crash

**Comment by MalakasPlayzMC** [comment]
It says 404 error

**Comment by ExaSonit** [comment]
It's not true 
It says: Hello BlueLight

**Comment by MalakasPlayzMC** [comment]
Before it was saying 404 error, but how should BlueLight send there the crash reports there
