### ISSUE TITLE
inventory clear

### ISSUE THREAD

**Issue by mote166** [BlueLightJapan/BlueLight#369]
### Issue description
Write a short description about the issue
when u go to a creative world then go back to an adventure world the items in ur hotbar dont disappear
### Steps to reproduce the issue

1... go to a creative world and hold some items 

2... go back to any world ( survival or adventure ) and u will still have ur items 

### OS and versions

* PHP: 7.0.11
* Server OS: linux
* Game version: 1.0.7

my version (downloaded it from the master branch yesterday) :
PocketMine-MP-DerivedVersion 2.0dev 「BlueLight」 implementing API version 3.0.0 for Minecraft: PE v1.0.7 alpha (protocol version 107)

### Crashdump, backtrace or other files

* ...

here are some other issues im having since i installed bluelight (i was using tesseract):

- when i die or teleport from a world to another sometimes i get stuck (the world doesn't load) . i think it happens because bluelight loads alot of chunks when the client gets into a world , i noticed that cuz the previous softwares i used were loading a medium amount of chunks but bluelight loads alot .

- i use advanced kits plugin and it worked fine before i changed to bluelight (i was using tesseract) but now when i touch a kit sign or get a kit by command i only get the armor but without the items . it can be solved by going back to spawn and then going to the world i got the kit from and touch or write the kit command then i get all the items i should get .

**Comment by mote166** [comment]
also when i switched from tesseract 1.0.6 to bluelight a player with mods hacked the inventory somehow and placed fire and lava everywhere (i got a backup already so it doesn't really matter) but i just don't want it to happen again. i think this inventory bug has something to do with how he did it .

**Comment by ExaSonit** [comment]
You can download a plugin that allow you to clear an inventory to a player

**Comment by mote166** [comment]
like what? i have but this is a bluelight bug which doesn't fully clear the player's inventory after changing gamemodes .

**Comment by ExaSonit** [comment]
The plugin is essentialpe but this bug probably is caused by a plugin, send a list of the loaded plugins on your server

**Comment by mote166** [comment]
Plugins (44): KillMoney v1.5, Broadcaster v1.16, 1vs1 v0.0.5, PurePerms v1.3.5, ServerAuth v2.13, ClearLagg v1.1.0, TimeCommander v2.1, PvPWorlds v1, SlapperRotation v1.0.1, DevTools v1.11.0, BanWarn v1.2.1, MSpawns v1.4, Rotater v1.1.0, NoExplode v1, ColorMatch v1.1.2, CoreProtect v0.1.5, AntiSpam v1.3, WorldEdit+ v0.01, WorldFixer v1, EconomyAPI v2.0.9, NoAdvertisingPE v1.0.1, Whois v3, WorldProtect v2.2.0, SignChanger v1, TapToDo v2.2.1, FlyCommand v1.0.0, iProtector v3.1b, BBDoDo vNetherBox, SAC v3.2.1, AdvancedKits v5.0b1, ManyWorlds v2.0.3, Slapper v1.3.3, EssentialsPE v2.0.0, BlockCmdPE v1.0.0, PmChair v1.3, DisguiseMe v1.1, NobadWordsKHAV v1.0.3, EnderParkour v1.0.0, LiveTexts v1.4pre, SW_svile v0.6dev, EDB

**Comment by ExaSonit** [comment]
Probably you have settend on "true" some bluelight's settings

**Comment by ExaSonit** [comment]
An option that not changes the inventory on new gamemode event

**Comment by ExaSonit** [comment]
Alright I found it, go to your server's files and open the file: bluelight.properties
![img_20170429_190605](https://cloud.githubusercontent.com/assets/20334614/25557285/edb54598-2d0e-11e7-911c-95f985345804.png)
Try to turn off 'keepinventory' and restart the server.
P.S where you found worldedit+?

**Comment by mote166** [comment]
its already set to "off" . i don't really remember i had it along time ago

**Comment by ExaSonit** [comment]
can you explain better the problem? Probably i don't understeand

**Comment by mote166** [comment]
i can reproduce it again too . it happens when u go to a creative world (for me i go to the plots world) and put any item in my hotbar then go back to the spawn by any teleportation plugin and i still have the item in my hotbar and i can use it even if the spawn is protected (i use world protect plugin and the spawn is in adventure mode)

**Comment by mote166** [comment]
another issue : i use advanced kits plugin and it worked fine before i changed to bluelight (i was using tesseract) but now when i touch a kit sign or get a kit by command i only get the armor but without the items . it can be solved by going back go spawn and then going to the world i got the kit from and touch or write the kit command then i get all the items i should get .

**Comment by mote166** [comment]
going back to spawn "

**Comment by mote166** [comment]
another issue : when i die or teleport from a world to another sometimes i get stuck (the world doesn't load) . i think it happens because bluelight loads alot of chunks when the client gets into a world , i noticed that cuz the previous softwares i used were loading a medium amount of chunks but bluelight loads alot .

**Comment by mote166** [comment]
please read the isuue again i added more i issues im having . i hope they can get fixed

**Comment by Qimie** [comment]
Or u set allow-cheat to true...... In what file i dont remember. Thats
allow toolbox player to hack.

**Comment by ExaSonit** [comment]
Simple. Use my plugin for worldinventory
https://github.com/ExaSonit/WorldInventory
Open WorldInventory_EN branch

**Comment by ExaSonit** [comment]
For the spawn, try to find a plugin like perworlgamemode (you can find it on github)

**Comment by ExaSonit** [comment]
@Qimie probably you mean allow-flight not allow-cheat
This can be find in "server.properties"
P.S. @mote166 put spawn protection to the value: -1 to disable it and use a plugin for area (commands: /area pos1 /area pos2 and follow the sintax - plugin is iProtector)

**Comment by mote166** [comment]
@ExaSonit i already put spawn protection to -1 and the world protect plugin works just fine . the issue started to happen once i installed bluelight so its not a plugin issue .

**Comment by ExaSonit** [comment]
Well probably the problem is plot plugin

**Comment by ExaSonit** [comment]
And then... How players tp to the hub without plugin?? It's strange

**Comment by mote166** [comment]
they teleport by many worlds plugin . and as i said , this issue only occurs with bluelight .

**Comment by mote166** [comment]
i switched back to tesseract until they fix these issues . i can't keep using it with these issues . i just need the two issues get fixed 1- the chunks issue and the inventory issue . maybe u guys should check tesseract's code and try to fix these issues .

**Comment by mote166** [comment]
this repository seems to be dead :~

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
