### ISSUE TITLE
Auto timezone?

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#371]
Can you make it auto?For example if you are in Europe etc.

**Comment by ExaSonit** [comment]
It's a good idea but in difficult

**Comment by ExaSonit** [comment]
The pc hasn't a GPS, this is the problem
Bluelight cannot get you position without GPS

**Comment by kametan0730MC** [comment]
It may be possible to identify the country from the IP address

**Comment by shoki-3738** [comment]
Although it will be slightly displaced, it is possible to acquire a country without confusion

**Comment by ExaSonit** [comment]
@kametan and if (like me) change ip address every day?

**Comment by poustmal** [comment]
This isn't a problem,timezone will not change because internet its a bit like a gps,idk if this is stupid or wrong,but that's my opinion.

**Comment by kametan0730MC** [comment]
We'll do it if we are free
