### ISSUE TITLE
Very important

### ISSUE THREAD

**Issue by ExaSonit** [BlueLightJapan/BlueLight#373]
Redstone doesn't work and the pistons don't exist!!!!
![img_20170430_124403](https://cloud.githubusercontent.com/assets/20334614/25563738/bef4e3a0-2da2-11e7-9dc8-a2c27d23cf8e.png)
![screenshot_2017-04-30-12-38-23](https://cloud.githubusercontent.com/assets/20334614/25563743/d01d69c2-2da2-11e7-9e14-5e625602fa1b.png)

**Comment by ExaSonit** [comment]
At first image on the sign: not work and I can't drop items on pressurplate

**Comment by caspervanneck** [comment]
yes becaus its not impleted

**Comment by ExaSonit** [comment]
Add it please

**Comment by ExaSonit** [comment]
Resstone is very useful

**Comment by poustmal** [comment]
Genisys had redstone but is laggy now,if someone add it here,fix it if its possible.

**Comment by kametan0730MC** [comment]
We cannot do it.

**Comment by ExaSonit** [comment]
Why?...

**Comment by ExaSonit** [comment]
Why you can't implement redstone?

**Comment by haniokasai** [comment]
@ExaSonit because it is heavy for PocketMine to handle it.

**Comment by kametan0730MC** [comment]
I'll do it if I am free
