### ISSUE TITLE
Crazy Minecart - Similar to #330

### ISSUE THREAD

**Issue by ExaSonit** [BlueLightJapan/BlueLight#375]
I can place minecart on the ground... why??? If I approach this minecart without binary, this starts moving alone, it moves until it finds an obstacle like a block
Similar to #330 
![img_20170501_192021](https://cloud.githubusercontent.com/assets/20334614/25587206/46ee8bd4-2ea3-11e7-9213-707716d086c4.png)

**Comment by kametan0730MC** [comment]
That's the specification
