### ISSUE TITLE
I found a new bug

### ISSUE THREAD

**Issue by ExaSonit** [BlueLightJapan/BlueLight#376]
Players can take items from item frame also if they aren't op

**Comment by shoki-3738** [comment]
it
Do you want to prevent Item from being taken from Player other than op?

**Comment by ExaSonit** [comment]
Yes... possibly

**Comment by shoki-3738** [comment]
How about trying to make a plugin?

**Comment by Qimie** [comment]
Why dont you make a default perm.... Easier right.... Make the perm as
default: true......Think outside the box pls....

**Comment by ExaSonit** [comment]
No @shoki-3738 , insert the code into bluelight
