### ISSUE TITLE
Splash Potion does not work

### ISSUE THREAD

**Issue by ZGamerOficial** [BlueLightJapan/BlueLight#378]
### Issue description
I put in bluelight.properties: splash potions: true, but in game does not appear splah potions.

### Steps to reproduce the issue

1...Put splash potions to true in bluelight.properties

2...Join the server and see inventory and search splash potions

### OS and versions

* PHP: 7.0.13
* Server OS: This server is using PocketMine-MP-DerivedVersion 2.0dev BlueLight implementing API version 3.0.0 for Minecraft: PE v1.0.7 alpha (Protocol versión 107)
* Game version: 1.0.7(android)

### Crashdump, backtrace or other files

* ...

**Comment by ExaSonit** [comment]
splash potion aren't added yet

**Comment by ZGamerOficial** [comment]
and other thing: mobs dont move when EntityAI is enabled and creepers does not throw nothing when you kill them

**Comment by ExaSonit** [comment]
i know this problem... download the ai branch

**Comment by ExaSonit** [comment]
https://github.com/BlueLightJapan/BlueLight/tree/ZombieAI
here

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
