### ISSUE TITLE
Update to 1.1.0.9?

### ISSUE THREAD

**Issue by ZGamerOficial** [BlueLightJapan/BlueLight#379]
### Issue description
Many servers are compatible with the lastest version of mcpe, but where i can found a software with the lastest version

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by ExaSonit** [comment]
Check 1.1.0-Update Branch

**Comment by ZGamerOficial** [comment]
can you put the download here? for windows

**Comment by ExaSonit** [comment]
https://github.com/BlueLightJapan/BlueLight/tree/1.1.0-Update
You need to use only src folder

**Comment by ZGamerOficial** [comment]
ok thanks! can close this issue

**Comment by ZGamerOficial** [comment]
see this:
[22:18:06] [Server thread/CRITICAL]: An Exception was ocurred when ejecuting command make 'makeserver' at  makeserver: Class pocketmine\network\mcpe\protocol\ProtocolInfo not found
[22:18:06] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\network\mcpe\protocol\ProtocolInfo not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by ExaSonit** [comment]
No!!! Don't do /makeserver command! It cause crash for now...

**Comment by ExaSonit** [comment]
Probably tomorrow I'm going to fix it

**Comment by ZGamerOficial** [comment]
srry, can you explain me how to install the src, i dont know xD

**Comment by ExaSonit** [comment]
Sorry, now I am out of home, at 20:00 (in italy) I explain you

**Comment by ExaSonit** [comment]
I cannot send you .phar file, can you contact me on Telegram? My nickname is @ExaSonit

**Comment by ZGamerOficial** [comment]
yes and my telegram is @ZGamerOficial

**Comment by mote166** [comment]
copy only the src to ur pocketmine main files but make sure that therea no "Pocketmine-MP.phar" in it

**Comment by mote166** [comment]
copy only the src to your pocketmine main files but make sure theres no "Pocketmine-MP.phar" in it .

**Comment by ExaSonit** [comment]
Command makeserver doesn't work with bluelight, you need devtools to make a phar for bluelight and rename it PocketMine
