### ISSUE TITLE
Setting hungertime

### ISSUE THREAD

**Issue by KromeThirty30** [BlueLightJapan/BlueLight#380]
How can i remove the hunger? In blulight properties,,i turned off the food but the hunger still there

**Comment by ExaSonit** [comment]
Swith difficult to 0 value

**Comment by KromeThirty30** [comment]
My server is on survival already,but hunger still drops

**Comment by ExaSonit** [comment]
![img_20170505_142837](https://cloud.githubusercontent.com/assets/20334614/25745441/2a286494-319f-11e7-84e3-6e8056d87f3b.png)

**Comment by Driesboy** [comment]
difficulty not gamemode !

**Comment by ExaSonit** [comment]
I told difficulty but @KromeThirty30 understeand gamemode 🙄

**Comment by KromeThirty30** [comment]
Sorry..I set it the Difficulty=0 but the hunger wont stop drops..and that cause a problem that playwr cant hit another player in Kitpvp or other pvp

**Comment by ExaSonit** [comment]
@Driesboy have you some idea?

**Comment by Driesboy** [comment]
idk

Op 5-mei-2017 19:19 schreef "ExaSonit" <notifications@github.com>:

**Comment by caspervanneck** [comment]
i cant read sorry

**Comment by ExaSonit** [comment]
![img_20170507_140304](https://cloud.githubusercontent.com/assets/20334614/25780771/20292970-332e-11e7-9dc8-d0d350671c0e.png)
Reduce this value

**Comment by ExaSonit** [comment]
increase HungerTimer value to prevent rapid hunger drops

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
