### ISSUE TITLE
The Non Ops Cannot Break Blocks

### ISSUE THREAD

**Issue by ExplodingSquad** [BlueLightJapan/BlueLight#381]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by ExaSonit** [comment]
It's normal .-.

**Comment by ExaSonit** [comment]
Your problem is cased by a plugin?

**Comment by haniokasai** [comment]
spawn protection ? :(

**Comment by ExaSonit** [comment]
Are you use sw_svile???
