### ISSUE TITLE
Translate the Lang file to Greek

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BlueLightJapan/BlueLight#382]
I have already translated some phrases:

language.name=Ελληνικά
language.selected=Επιλέξατε την γλώσσα {%0} ({%1}) ως βασική

multiplayer.player.joined=Ο/Η {%0} εισήλθε στο παιχνίδι
multiplayer.player.left=Ο/Η {%0} έφυγε από το παιχνίδι

chat.type.text=<{%0}> {%1}
chat.type.emote=* {%0} {%1}
chat.type.announcement=[{%0}] {%1}
chat.type.admin=[{%0}: {%1}]
chat.type.achievement=Ο/Η {%0} μόλις κέρδισε το επίτευμα {%1}

disconnectionScreen.outdatedClient=Παρακαλούμε αναβαθμήστε την έκδοσή σας για να μπήτε σε αυτόν τον server!
disconnectionScreen.outdatedServer=Αυτός ο server χρησιμοποιεί μια παλιότερη έκδοση του Minecraft PE!
disconnectionScreen.serverFull=Ο server είναι γεμάτος!
disconnectionScreen.noReason=Αποσυνδεθήκατε από τον server
disconnectionScreen.invalidSkin=Λάθος εμφάνιση/skin!
disconnectionScreen.invalidName=Λάθος όνομα!

death.fell.accident.generic=Ο/Η {%0} έπεσε από κάπου ψηλά
death.attack.inFire=Ο/Η {%0} τυλίχτηκε στις φλόγες
death.attack.onFire=Η/Ο {%0} κάηκε μέχρι θανάτου
death.attack.lava=Ο/Η {%0} προσπάθησε να κολυμπήσει στη λάβα
death.attack.inWall=Ο/Η {%0} πέθανε από ασφυξία μέσα σε τοίχο

death.attack.drown=Ο/Η {%0} πνίγηκε
death.attack.cactus=Ο/Η {%0} τσιμπήθηκε μέχρι θανάτου
death.attack.generic=Ο/Η {%0} πέθανε
death.attack.explosion=Ο/Η {%0} ανατινάχτηκε
death.attack.explosion.player=Ο/Η {%0} ανατινάχτηκε από τον/την {%1}
death.attack.magic=Ο/Η {%0} σκοτώθηκε από μάγια
death.attack.wither=Ο/Η {%0} μαράζωσε
death.attack.mob=Το {%0} έσφαξε τον/την {%1}

**Comment by haniokasai** [comment]
@kametan0730MC  これいる？

**Comment by MalakasPlayzMC** [comment]
This is the Greek language file: https://github.com/BlueLightJapan/BlueLight/blob/master/src/pocketmine/lang/locale/ell.ini

**Comment by MalakasPlayzMC** [comment]
BTW, I don't speak Japanese so I used Google Translate so tell me if I didn't answer correctly

**Comment by kametan0730MC** [comment]
@haniokasai あって悪いことはないよ、一応追加しとこう

**Comment by kametan0730MC** [comment]
@haniokasai これってどこについかするの？

**Comment by haniokasai** [comment]
@kametan0730MC langフォルダかなぁ？

**Comment by MalakasPlayzMC** [comment]
What are we going to do? You could use google translate to translate the messages.

**Comment by haniokasai** [comment]
maybe we will not implement it....
