### ISSUE TITLE
How To Get Permission For Op Person Ingame

### ISSUE THREAD

**Issue by ExplodingSquad** [BlueLightJapan/BlueLight#383]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by MalakasPlayzMC** [comment]
Firstly, this is not an issue. Secondly, tell us more about that you need. I can't understand from the title.

**Comment by ExaSonit** [comment]
It's a issue....

**Comment by ExaSonit** [comment]
It is a valid issue

**Comment by ExaSonit** [comment]
By default, op permission is needed to all, try to check in your server's file the method: disable-op-ingame or something like that

**Comment by MalakasPlayzMC** [comment]
I told I can't understand from the title

**Comment by ExaSonit** [comment]
I referred to @ExplodingSquad ...

**Comment by MalakasPlayzMC** [comment]
Oh

**Comment by haniokasai** [comment]
it is not issue.
