### ISSUE TITLE
Noteblock still doesn't fully work

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BlueLightJapan/BlueLight#384]
### Issue description:
If I place it on a glass, sand, bedrock or oak wood it does the same sound that does on dirt. Plus, the melody I hear in the NoteBlock on the dirt is not full.

**Comment by ExaSonit** [comment]
It's normal...

**Comment by ExaSonit** [comment]
Try it in your persobal world. He's being the same thing (or similar)

**Comment by MalakasPlayzMC** [comment]
@ExaSonit No, it isn't. In my personal world I hear the click sound or the bass sound but in my server I hear the piano sound

**Comment by ExaSonit** [comment]
Maybe I will fix it

**Comment by MalakasPlayzMC** [comment]
Ok

**Comment by MalakasPlayzMC** [comment]
Do you know how?

**Comment by ExaSonit** [comment]
I need to see code

**Comment by MalakasPlayzMC** [comment]
Ok
