### ISSUE TITLE
Item duplications/glitch 

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#386]
![screenshot_2017-05-13-14-31-36](https://cloud.githubusercontent.com/assets/22281205/26025234/cac37842-37eb-11e7-8ac4-fdfa319865ee.png)

**Comment by poustmal** [comment]
When using armour.

**Comment by ExaSonit** [comment]
It's simply a glitch

**Comment by poustmal** [comment]
I mean its bug

**Comment by MalakasPlayzMC** [comment]
I will try to fix it
