### ISSUE TITLE
Add DeviceOS, make BlueLight to say the client Id of someone that joins and the device he/she uses

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BlueLightJapan/BlueLight#387]
Add DeviceOS, make BlueLight to say the client Id of someone that joins and the device he/she uses.
Elywing has this feature, so you could steal code from there since it is dead

**Comment by poustmal** [comment]
Seems that loginpacket.php file has sth for device os but it doesnt do sth.i tried a bit to copy-paste but i stuck there,

**Comment by kametan0730MC** [comment]
You can $player->getOS();

**Comment by MalakasPlayzMC** [comment]
I have a modified version of Elywing for MCPE 1.0.5 + 1.0.6 + 1.0.7 + 1.0.8

**Comment by MalakasPlayzMC** [comment]
@kametan0730MC Because I don't want to create a new issue, can you tell me we're could I get BlueLight for 1.0.4?

**Comment by kametan0730MC** [comment]
https://github.com/BlueLightJapan/BlueLight/tree/ba560e6882523af208d96c3ef6d96341d486e1dc

**Comment by kametan0730MC** [comment]
You can install from here

**Comment by AppleDevelops** [comment]
If you need any help adding it, here.
https://github.com/TesseractTeam/Tesseract/commit/15252a4a041d66b6813c38984783d74852dae9b9
