### ISSUE TITLE
Anvil:

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#388]
![screenshot_2017-05-14-00-36-15](https://cloud.githubusercontent.com/assets/22281205/26029453/05e6e9e8-383e-11e7-8f05-f23f9dea73b8.png)

![screenshot_2017-05-14-00-36-05](https://cloud.githubusercontent.com/assets/22281205/26029467/71dc15e2-383e-11e7-9791-c91aaa790e46.png)

**Comment by poustmal** [comment]
this when I place anvil,and stays like that,and i should break the up anvil and then second and third,(bad english or explanation,sry)

**Comment by ExaSonit** [comment]
I found the same bug with sand, if i put two blocks of sand (one over the other) and I break the under sand, the sand duplicate itself and I can repeat this action for infinity!!

**Comment by poustmal** [comment]
pmmp has fixed this

**Comment by poustmal** [comment]
pmmp seems that has fixed this.

**Comment by poustmal** [comment]
Add a fix from tesseract if its possible someone,they have a commit with a fix

**Comment by poustmal** [comment]
oops,wrong reference issue.

**Comment by poustmal** [comment]
Idk how,but now is fixed on re-create branch.

**Comment by poustmal** [comment]
and anvil falls like pmmp,close issue
