### ISSUE TITLE
Nether portal doesn't work

### ISSUE THREAD

**Issue by ExaSonit** [BlueLightJapan/BlueLight#392]
Nether portal can't be actived
![img_20170516_231039](https://cloud.githubusercontent.com/assets/20334614/26128563/1b3b6188-3a8d-11e7-88da-4245d30444fb.png)

**Comment by poustmal** [comment]
I think I can make flint and steel activate the nether portal,but you won't be able to join.

**Comment by Driesboy** [comment]
The nether is not good implemented yet

**Comment by ExaSonit** [comment]
Ok, thank you
