### ISSUE TITLE
Mobs dont spawn

### ISSUE THREAD

**Issue by daniktheboss** [BlueLightJapan/BlueLight#393]
Hi i downloaded the latest src and when i use an egg it doesnt spawn.

**Comment by akaSnapy** [comment]
Happens to me too

**Comment by kametan0730MC** [comment]
It was possible in my environment

**Comment by akaSnapy** [comment]
I just figured out if you use PEX mob eggs will work

**Comment by poustmal** [comment]
Enable mob ai on bluelight.properties file

**Comment by daniktheboss** [comment]
I did

**Comment by poustmal** [comment]
..well i dont have any idea.

**Comment by akaSnapy** [comment]
If u have a MobAI plugin disable it.

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
