### ISSUE TITLE
The rails and minecart is error

### ISSUE THREAD

**Issue by beuttieu2808** [BlueLightJapan/BlueLight#399]
Hi, i use the lasted version, and when i us rails and minecart to build, the server is said:

`**Notice: Undefined offset: 10 in phar:///home/vdesktop/BlueLight/BinaryPackforLinux-x64-master/BlueLight-PHP7.phar/src/pocketmine/block/Rail.php on line 193

Notice: Undefined offset: 10 in phar:///home/vdesktop/BlueLight/BinaryPackforLinux-x64-master/BlueLight-PHP7.phar/src/pocketmine/block/Rail.php on line 199

Warning: in_array() expects parameter 2 to be array, null given in phar:///home/vdesktop/BlueLight/BinaryPackforLinux-x64-master/BlueLight-PHP7.phar/src/pocketmine/block/Rail.php on line 199

Notice: Undefined offset: 10 in phar:///home/vdesktop/BlueLight/BinaryPackforLinux-x64-master/BlueLight-PHP7.phar/src/pocketmine/block/Rail.php on line 208

Warning: in_array() expects parameter 2 to be array, null given in phar:///home/vdesktop/BlueLight/BinaryPackforLinux-x64-master/BlueLight-PHP7.phar/src/pocketmine/block/Rail.php on line 208**`

**Comment by ondraczsk** [comment]
is the php ok?

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
