### ISSUE TITLE
hunger dont go down  and no xp comand

### ISSUE THREAD

**Issue by caspervanneck** [BlueLightJapan/BlueLight#4]
fix it plz

**Comment by haniokasai** [comment]
really? ill check it.

**Comment by kametan0730MC** [comment]
I will fix it,thank you for your opinion.

**Comment by caspervanneck** [comment]
@kametan0730MC can you fix the hunger from Players they go dead bij regeneration

**Comment by caspervanneck** [comment]
And te hunger bar dont go down

**Comment by kametan0730MC** [comment]
Ok

**Comment by Ogiwara-CostlierRain464** [comment]
In Additionaly, also weather command dosen't work.
I'll fix it from now on.

**Comment by Ogiwara-CostlierRain464** [comment]
Hunger bug fixed.

**Comment by kametan0730MC** [comment]
Fixed
