### ISSUE TITLE
Shutdown of protection from a track

### ISSUE THREAD

**Issue by veme312** [BlueLightJapan/BlueLight#400]
hi! I need to turn off protection from a track and opening of chests in a creative. such hasnt found an opportunity how to be?

**Comment by MalakasPlayzMC** [comment]
Are you able to open chests in survival gamemode?

**Comment by veme312** [comment]
No

**Comment by ExaSonit** [comment]
Disable spawn protection and use iprotector plugin to protect areas

**Comment by ExaSonit** [comment]
close issue pls
