### ISSUE TITLE
PlayerHungerChangeEvent does exist

### ISSUE THREAD

**Issue by VoltexYT** [BlueLightJapan/BlueLight#401]
PlayerHungerChangeEvent does exist please help 

    public function onHungerEvent(PlayerHungerChangeEvent $event)
    {
        $event->setCancelled(true);
    }
[Server thread/CRITICAL]: ReflectionException: "Class pocketmine\event\player\PlayerHungerChangeEvent does not exist" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 704

**Comment by ondraczsk** [comment]
playerhungerchange event isnt on pm since mcpe 0.16, but if you need this, you can use our system, we implented PlayerHungerchangeevent https://github.com/ImagicalMineReactive/ImagicalMine

**Comment by caspervanneck** [comment]
@ondraczsk  don't make reclame for own software
