### ISSUE TITLE
ADD COMMAND BLOCKS

### ISSUE THREAD

**Issue by ExplodingSquad** [BlueLightJapan/BlueLight#405]
### Issue description
Need Command Block For More Fun In The Server

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by akaSnapy** [comment]
Well still kids can't understand adding command blocks on PHP is more harder then everything

**Comment by ExaSonit** [comment]
use a plugin, close issue

**Comment by armagadon159753** [comment]
It is strictly useless

**Comment by ExplodingSquad** [comment]
I Just Created A Plugin Command Blocks And Code For Bluelight Phar Close!!!!
