### ISSUE TITLE
Anticheat on/off?

### ISSUE THREAD

**Issue by poustmal** [BlueLightJapan/BlueLight#409]
Can someone add on/off anticheat because my server seems that doesn't have anticheat protection and I have eaten many griefs in one day,but I have world protect plugin that works(I don't mean anti-movement hack or insta-break if someone tell this)

**Comment by MalakasPlayzMC** [comment]
You could use SAC: https://github.com/DarkWav/SAC

**Comment by haniokasai** [comment]
anti cheat is too heavy,we will not implement it.
