### ISSUE TITLE
1.1 Update? My server is dying for it

### ISSUE THREAD

**Issue by XDqrkneZ** [BlueLightJapan/BlueLight#414]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1... Title says everything 

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by alexbgameson** [comment]
Here's a link to the 1.1.0 version. https://1drv.ms/u/s!Akcvd2KC-M5JhoBohhsQPl8fyu87hQ

**Comment by DeathRaven359** [comment]
This .phar file crashes my server whenever players join. I have no plugins installed.

**Comment by MalakasPlayzMC** [comment]
please close

**Comment by ExaSonit** [comment]
use pocketmine for now, bluelight is in "re-create" fase
