### ISSUE TITLE
Add sendTitle(""");

### ISSUE THREAD

**Issue by armagadon159753** [BlueLightJapan/BlueLight#418]

**Comment by ExaSonit** [comment]
Why?

**Comment by armagadon159753** [comment]
I have plugins that use this

**Comment by ExaSonit** [comment]
It's already added

**Comment by armagadon159753** [comment]
I ise last SRC but console sey an error

**Comment by ExaSonit** [comment]
Maybe is your plugin

**Comment by armagadon159753** [comment]
Nop he is correct !?

**Comment by ExaSonit** [comment]
What is the error?

**Comment by armagadon159753** [comment]
![_20170605_204555](https://cloud.githubusercontent.com/assets/25569806/26798223/ffc98378-4a2f-11e7-9ff5-f78329e4f08d.JPG)

**Comment by Qimie** [comment]
Now hes quite. and dont dont be shy to tell that u make a mistake. I hate
people that doesnt want to tell people that they made mistakes.

**Comment by ExaSonit** [comment]
In a plugin a player cannot send a title...

**Comment by ExaSonit** [comment]
Try $this->player->sendTitle("args");
