### ISSUE TITLE
pocketmine/utils/Binary threw a critical error when a player joined.

### ISSUE THREAD

**Issue by chell-uoxou** [BlueLightJapan/BlueLight#421]
### Issue description
pocketmine/utils/Binary threw a critical error and BlueLight crash when a player joined.

### Steps to reproduce the issue

1... When MCPE version was 1.0.9, Tesseract was running smoothly.

2... The MCPE update 1.1 came, so I tried to run BlueLight without resetting plugins and settings.

3... When I join to my server, the server throw the error (written in "Crashdump, backtrace or other files") and shutdown.

### OS and versions

* PHP: 7
* Server OS: Ubuntu 16.04
* Game version: iOS MCPE 1.1.0

### Crashdump, backtrace or other files

error text:
 [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\Binary::writeVarLong_64() must be of the type integer, null given, called in /home/*******/src/pocketmine/utils/Binary.php on line 650" (EXCEPTION) in "/src/pocketmine/utils/Binary" at line 677

**Comment by caspervanneck** [comment]
first of allwe arent  Tesseract and  yes i have it to

**Comment by chell-uoxou** [comment]
@caspervanneck Uh, Oh, I see. Sorry.
But I thought it may be important to report this bug.

**Comment by chell-uoxou** [comment]
Umm...
