### ISSUE TITLE
client flood + glich?

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [BlueLightJapan/BlueLight#422]
There is something wrong with server:
1. If you are online for 15+ minutes and walking, the client will crash on Android, and on W10 will use all cpu+ram from pc (dual core 2.5ghz and 4gb ram), and the pc will freeze.
It never happened on older versions.

2. Sometimes you are kicked from server, maybe timeout? But u can still walk in server, but cant chat or nothing uptade, like terrain, I checked console and I was not even online and ppl were chating, so it was not a crash,from my guess timeout kick, because I saw many players kicked from timeout at once, I stayed in server a little longer then I relogin and all was normal.

3. Inventory random reset. Maybe is a plugin fault so u can ignore this.

**Comment by Qimie** [comment]
Can u try it back with many players but without any plugin this time.
Please.

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
