### ISSUE TITLE
Monster spawner?

### ISSUE THREAD

**Issue by HipsterAF** [BlueLightJapan/BlueLight#423]
### Issue description
Monster spawner doesn't work, can you add?
### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by ExaSonit** [comment]
mob works?

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
