### ISSUE TITLE
Potion

### ISSUE THREAD

**Issue by Donquih0te** [BlueLightJapan/BlueLight#425]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP: 7.1
* Server OS: Debian
* Game version: 1.1.0

### Crashdump, backtrace or other files

* ...
When using a damage potion

Argument 1 passed to pocketmine\entity\Living::damageArmor() must be of the type integer, float given, called in /home/gs22970/src/pocketmine/entity/Living.php on line 224"

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
