### ISSUE TITLE
crash of binary.php

### ISSUE THREAD

**Issue by caspervanneck** [BlueLightJapan/BlueLight#426]
PocketMine-MP-DerivedVersion Crash Dump Sat Jun 10 16:24:28 UTC 2017

Error: Argument 1 passed to pocketmine\utils\Binary::writeVarLong_64() must be of the type integer, null given, called in /home/minecraft/multicraft/servers/server3/jar/pocketmine/src/pocketmine/utils/Binary.php on line 650
File: /src/pocketmine/utils/Binary
Line: 677
Type: notice

Code:
[668] 		return self::writeUnsignedVarLong_32($v);
[669] 	}
[670] 
[671] 	/**
[672] 	 * 64-bit VarLong encoder.
[673] 	 *
[674] 	 * @param int $v
[675] 	 * @return string
[676] 	 */
[677] 	public static function writeVarLong_64(int $v) : string{
[678] 		return self::writeUnsignedVarLong_64(($v << 1) ^ ($v >> 63));
[679] 	}
[680] 
[681] 	/**
[682] 	 * Writes a 64-bit integer as a variable-length long
[683] 	 *
[684] 	 * @param int|string $v
[685] 	 * @return string up to 10 bytes
[686] 	 */
[687] 	public static function writeUnsignedVarLong($v) : string{

Backtrace:
#0 /src/pocketmine/utils/Binary(650): pocketmine\utils\Binary::writeVarLong_64(NULL )
#1 /src/pocketmine/utils/BinaryStream(333): pocketmine\utils\Binary::writeVarLong(NULL )
#2 /src/pocketmine/network/mcpe/protocol/DataPacket(268): pocketmine\utils\BinaryStream->putVarLong(NULL )
#3 /src/pocketmine/network/mcpe/protocol/AddEntityPacket(68): pocketmine\network\mcpe\protocol\DataPacket->putEntityUniqueId(NULL )
#4 /src/pocketmine/network/mcpe/RakLibInterface(193): pocketmine\network\mcpe\protocol\AddEntityPacket->encode(boolean)
#5 /src/pocketmine/Player(1088): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
#6 /src/pocketmine/entity/Bat(55): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object)
#7 /src/pocketmine/Player(825): pocketmine\entity\Bat->spawnTo(pocketmine\Player object)
#8 /src/pocketmine/level/Level(2497): pocketmine\Player->sendChunk(integer 67, integer 39, pocketmine\network\mcpe\protocol\BatchPacket object)
#9 /src/pocketmine/level/format/io/ChunkRequestTask(88): pocketmine\level\Level->chunkRequestCallback(integer 67, integer 39, pocketmine\network\mcpe\protocol\BatchPacket object)
#10 /src/pocketmine/scheduler/AsyncPool(158): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
#11 /src/pocketmine/scheduler/ServerScheduler(351): pocketmine\scheduler\AsyncPool->collectTasks(boolean)
#12 /src/pocketmine/Server(2532): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 1841)
#13 /src/pocketmine/Server(2298): pocketmine\Server->tick(boolean)
#14 /src/pocketmine/Server(2180): pocketmine\Server->tickProcessor(boolean)
#15 /src/pocketmine/Server(1759): pocketmine\Server->start(boolean)
#16 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/multicraft/servers/server3/jar/pocketmine/, string /home/minecraft/multicraft/servers/server3/, string /home/minecraft/multicraft/servers/server3/plugins/)

PocketMine-MP-DerivedVersion version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux vps 2.6.32-042stab094.8 #1 SMP Tue Dec 16 20:36:56 MSK 2014 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
DevTools 1.11.3 by PocketMine Team for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
Parkour 1.5.2 by jdcraft for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
Functions 1.2.1-new by Ad5001 for API(s) 2.0.0, 2.1.0, 3.0.0
SimpleAuth 1.8.1 by PocketMine Team, shoghicp, awzaw for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
SkinChanger 1.3.15 by SalmonDE, Aericio, KairusDarkSeeker for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
EconomyAPI 5.7.1 by onebone for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
PurePerms 1.4.0-INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0, 2.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
EconomyShop 2.0.8 by onebone for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
FaceLogin 1.0.0 by Muqsit for API(s) 2.0.0, 3.0.0, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA67
EssentialsPE 2.0.0 by  for API(s) 3.0.0-ALPHA6
Slapper 1.3.4 by jojoe77777 for API(s) 3.0.0-ALPHA6
WorldFixer 1.0.1 by CreeperFace for API(s) 1.0.0, 2.0.0, 3.0.0, 3.0.0-ALPHA4, 3.0.0-ALPHA5
TitleJoin 1.1 by  for API(s) 3.0.0-ALPHA5
BigBrother 1.6.0-beta by shoghicp for API(s) 3.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 3.0.0-ALPHA5
ZipPluginLoader 1.2.1 by aliuly for API(s) 3.0.0-ALPHA5
iProtector 3.1b by LDX for API(s) 3.0.0-ALPHA5
TapToDo 2.2.1 by Falk for API(s) 3.0.0-ALPHA5
SimpleAuthHelper 2.0.5 by aliuly for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
PureChat 1.4.1 by 64FF00 for API(s) 1.13.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtXI1z2zaW/1cwcufW7oiSKFkfVteZc21nm10n8cVOs3PVXgYiIYkxSTAEaVnt5X+/9x4AEpTi
xHGze725ZKYNAQIP7/3wPkEov7WKKBGtqX94NPZ9fzKatFsxV8V5nsu8Nf2tVWwyeN1KZREFotVu
JUIpvsSuk3xZJiItmM8yrpQIWSFZJoMbUSRRKmazsohiNZv9GKU830yn6zwqxM88v5Dp8u3ocP+A
JaUq2FwwuWDFSjBcikVpIZYib7O0jGO2jG5F2mYBj2OgH6Wsu5KJ6CL9IOeLopuUMTBGj0rktyJX
5u9B9x3PuzU7XZUHbpOY62reOtkqYzJlMbxgo2EPxFzA6k+jGOX8py2Jy5glPjESRiFfreloPG63
ipzDNkx/ae312Kdm7YMYB9Mv2Y4Xry8u2AGstud/kvJVkQue7A8Gg4fTd4j3d4inoljL/KabBJno
ZrksZCDj7hkv+CXHQfv90eRTS2mGvCdZWewuN3jgcidheJ4WUbExa+4saabNZjhvNrMTZ7OaUWJB
U3mdRu9L8Sx0ODn8NCev+M1FNH8G2p8vYIv3/aPBQznY4t17ItJAhmJ/LmUseEqrD3dWv4z5RuT7
fm/yGVG3OCMpDUruLE2Pyfk7ERTtR3FeTTacs/qJhBjtCCFodvdHXuwPh1tiaIa8J2GtSb+DKWJg
fB+Kk/726poz0FEOG6Iyvk6v5f14EfXJDvVY3Iq4e4H/3++Dh75HQiXS8HRVpjf7xnuy0bhtPSkb
HD1wN4DVYLUr9NE9bC1knvCiG8kurf1KgMar4pqrm/0dlaIZsxlJ4j0JnPGn4NrnsOY/hXV/10mq
YCXCMhZ590Rt0uAS9GvfH97DrxZxNovkbLYtpPdEpqcyyWJRRDJtbO0VhYMGI/4nGNHDr2x7fzD0
t9ipxoJ2Wq4BRglRMSBmVMPY/V0nq9fY7w8H/ftpbzHiPUl4lF6vwL2GPwmeF3MBdmb3xp8c+nq1
wb2r9Y+2gdVvvCcQQW+aPB/eS8Wf9D5B5TKXAeQkMm+SG95Hzh8Pj+4hpwoQsklm1+Vc0uNzeNw/
POrfQ+nt20CmqsjLoNj/kStxCjmVupA8vMdDmoD2HPC+kMulMwqIROnyd+Q9jyHxmDlZXC6jVHUP
Wv/40G6J/+/545cldoCYxq81XfBYiXYLIzjiNxpNgM6smEGWU5R5ypSIFwaM16mKlqkILSiD/v53
twc/AOHR6IhmfcDncQ+e6cGnzu7331OrTy32PRsdevOoYIYM0+lD3qFBAzOIGod2xr9nPOcJgs2+
u6VXw+qV5ZM0iN6NzLsutcbUysp5HAUwigP+bFGmAbpRtr3JeoUDNjX0fiMSD4cESAAm7M9/Zv4B
+y+Gz0+esNHgQMM0dmCaWJgmDZgmFUxvcAHFuMXLekKOfbc8j/g8Fl4s0mWxYrHUwk9cACcfAfC/
jalpHCf34MjKDM0DAtp8A0zQ0Aask8/DuoXNfhPXD9+Ki2/Fxbfi4ltx8a24+FZcfCsuvhUXf9Di
ot1ailTkPMbsOOV4eN2qYfOeX3pnIoe0P/wZCIDxANK35mna8jujTj8UmGrNyygOW9MeZN7G0ltT
3x+0WzyLYOSg0+v0vJOLy59OhjB6GRXQ2XvgH5iQ85s4muOczqSDHaXh9SJKyzt2mynWB2YGfa93
2AfdmPeODjsTBvnR1fNLdl0KdiYCBirS700Ho+lwxJ5f/Q0aoMp3kxHkVEASz5CnrTFwOoDWr+Co
LeP65Vup7ILQQY2YGlW5oRDEM3F7DWqpHECrriZ4vk8r8bJYyVxhplgjz64hUcLtIfx+afUNHw6Q
frPZbzYHzeZhszlE0iLFFBukBOWHGikUGciMfMA7JRfFmduB/sURBZKpWqgYrAXeXV2fvLp+fQkd
azFXkFJC36ooMjXtdmHHV+W8E8jEscpuRQMgvOT5jSxzVw9NTxO1YaffBO1dSFr+BwTLcAbRT0ui
vUYN2OXLq+s3L19dnLmQYaUNcDw1xYarR3VfE5J+x/dSsW7CchIOez3/I6jA6Bqdx4qmqc9mFUtf
IttVhLH4BHh1hHM6m9JNOv6nrQS4XMnlKgrwGxBf/8rXf0BdqMWD0OOK+mjjcaggpjdRerriKQQk
F1Snt4nqoOMPm7Be8TiR6dk59J6Azw8iCU9/41FeqjPQ3yshboDKHxBZwzfgWkurG59RxwpgRSRC
0QlFF8E8h5RAJpuTy2cOlk6nC+WwM95WUJmKOfz3B8TKcAY1jxYG2JvNGoI9wHwvy1xcijxxXVPd
11SzQ2D52Yuz85+bCI0Onz7t9di/MUgJMXl6li6iFIowBzKIjwPjrz7it/4XMXyrmYeazsrsPD5U
41yTxrkmI6vp1Fp4tZLZrhpSr4s1wjT5Q+mhazFfoJPgzLNKKY2YDwmYPBCQkCPJOmBWfU2t1CA4
SD0v3wOx+4D6DAaN5mirOX6smmmWIMI6MjwAhnOl8DyDx+ry3NUat3tbbZpg1CA0xHqkGO7Cs5mu
qx5hJBdQyKbhy8Xz08vzbkMYjH0xz7Jm3DM92zHvcCt1lO+kGOOf1teVWun1H5QUfUzcmrGuFQXk
fCPzOHwa3TVEdTq3lXwrLJ3mAljNUaEafrbXcLMP0fhHolKzOps12H6AXl9HRSz+KhvmXfc5kkPc
+Kw2P1qCasUvSXd/jJY/QlG8amyb07ldUve8uSh4c++qDHdLnkcrqKGHJ/OWEff5ixPTeirm5E4T
Ffc5Tze04W7K4HQ2HZK/7Z15HJXxpvV1t1ITnc0SYGNNbHzJnv5nlOmYbTxaLdb2m51S7V8g2xYP
24I9cEufl1G+iEQcdrdlAgAiyNwKyNykK7vT6YoNtca8KfXF2d+/sshAcTar13+05wU6HgUZRxZ0
Pzy7lmfSdT6mp6m7O/v7lMc3X1nUgmeFDOVsVrPwRUX3TyLeipbbr7YThOFndPZfm1Y6he8D7HtF
Ij1aH3gs3vE0zCWQc85qPXuGWkBQ7SZcFfh1YBtHUyxBTVps1UrUtV0q+R8rkj5VEv1r8K6Lkh24
McOm4x8wFqD5d3EbyRKyMs/2t+6pm1D++ukrVE1E5gMexeJVAAHbYa2IDr07WS5hR4pI4Lnt3mXV
YqcSas8lwysms3yW7l3xgv21TPFygD+a9vt4WPz6+hQPi8c4IJFFeDwrez0+jvVfoxeCwic1Dk/L
uWAncbbi7NbHCZoBL5N5cewf+YMBdq5XIJkXR6o4lil28DSVZRqgYtGXQh6sInEr8EqPMkPo06SX
abcE4B77I2KI35lJ6tgHfJFYHMu1t4ij5apoTOZplEDa3OhL5Nx2LAG5RIbimKgsZA78VH16yIrn
YSBzaC4W2M5uM/MmjBaLKCjjYnNMIuoPC+A/PSWKIkqX6hi76Xudh6ZwTGG37lNChM4QvIB0fHb+
9OT1xTX2agX13pci35glTVcOtaLpwccOXoAC2uHx9/QH8CgL6Sl+a4W4jcTaCwF8DogfT2rIUtpJ
M0pmHihJEik0UY+YOqYdNVsUhbA2XviXZUF8F+KuAFX0Mh7cUAf4npiEtPhqSISnvzfBWIu8TPH2
kucAbTcnRdfS3LE0C2wHbj59e/FWgnbb0bgoA32bdIZQCPQnHaMa+C2j8mKdTRKjOTB0jiwgSyiB
QbzkggbBQAVY43MQmQi7XgklmN1WxnNBV8agilfwAAYUoDrTbbIoDeIy1NfFdkxRU7uSib11tk1V
8YVoM8ojFRJl81zwG7aRZW6osWjBALUIEhVcA1QzB+sAx0+kX4h1RbAbigUH9VRsLdM/FQzLKp4z
1I0E7/eABmzw3lmxipSWfr0SKSuzZc5DINBBkhpeTXCKDbaHX13xolIB+8Rini5LvhQMr3UQfGYz
VATtWMIq0a8EsJ58uhKBkac5FRixXk+knXV0E2UijHhH5ssutroXoL5v5eLts6uXb0eDI6//FucR
pBWpKZuBX1/OWnqxNytSb7z6hPcQGEhsvh7CtuU8haq10BcHDbbEL/ACT6KgLQ7BwweCrSAkxrTp
CZHWrqJelq7d0Ru1KotQoibrq4rIkvnoHsRSidAyd4IGyNAj4tdME17ZbcTZf6DF0yCyfRt6pwwj
lZ58tYK5HDVYSeDLrKU3kBtirFSgnhDXQEFIzpPLZzASwm2oUatfecDeHJhzlzgnX2NpgfwM3SAD
ZQZdQZbnG2Y0jCYY31S9d0HZexMB9GDzG8bDkIEb0HqJ7OKHcmCLK/AOdKETtHEuEBvYBvG+5DFu
EF3FZLc8LgXbN8tCiDog8npN8IsCg44HO4zfqafwXq/+okzm+N16weiKAt5KYHhZA4yso0e8xguk
qL1WXBy3yiXEKFAVvMXQZuTYmHFpoNBtACQBBMldEkAQwLEvKVOwLhxiqF+RMoFcYIK5vIOQVAiA
AsQiQ0gr9hBhy9KzBVoyDkKLbbOo+BNgWOQ0LxQYE0lDt2azfZACdp71NTYkiWeknRIta9cY5/KN
seq/xHIOUGO6w/QL0M2E7ilCe8np4mCHXWmWesREpHDLrVcA+dYRsUjwM4wvmpLdEUUoLSJQI3Bt
EF9SIrYAf2LX1CoBYpWk0EsJEkk0HsSPVloSox4xN2U9KwzbI59e0JWQ/wNiYJL4GSEw9fidQqhC
ZsSHcXAVX4aeYmB2+v50zRWua1nze/3DmjvIiiNJoQ2tVuHCATl0w2VlmT4sCM4p1DpIYzxMBKxN
mmAgU3B+YNGAJXqU+6DWEEMKGVOcQN+gh2nqmgpYam351o3pdV6i48G4SZM6uxMQCFMPAKyZCDC8
KgIKuda467mVKICtyFQt8qBnZFYH97BlEBjUCCx5Pgf98Mx1KfAY2ho/ijQpHLJkZjEzC+w94WlJ
4dzlBhKeEvTkoG39yI6iGE3RfnmxsB4lqXWww17qCEot0JaVLOOwYiUCv7NOWc2+1m2WEfcg6qjX
q6Vle0/JZnZ8K+mRplEJt8hlYp20nm1GeK5H29ppEMhs6K6afES7tmZjbkn3/5TdheccnHWZQMBK
8XqUzaBRPqaTYm1R9VKoSYa6MSlGJD3MqUpwwIcOs2dSv9zeUYwnmJhpOnqw1SFNzQz8quJTfPMC
KMSEBcAoi10UXzkpwmdJ4n/mXqSTO4IOxTrYzvFqJGU/dD1S4e1KZpwb2azOkM1b7dHmogq7BuA9
1w/ad+gz8k2B1NvM8x3N1+GVlvYKyw74peHIOqU6qFMNhNE01PuMWSSlPjgbOg1nHfYT1CIA+zGk
5qDhp5ev2zAXuJiD+1pHYbHSgcA4hmoBXWRN2bjKQuoMRRFEzuAOOwnBBFc8XnSh8tCJUyhADc1i
sCzDYwXcfceGnTTAodZIz87v0GIx++JxW/sDXPxNlEIqC+KBWgmyUkwsXl+mlzYtqQsJzLxw0hqC
BxEtszTzTEczHaTiWczLpVUKaZwvw0CUk/qLOxGUOstC74W30zrVW4V6QqlTtso6URrRjxuMnHaM
teE3PE/R+TuzsdIy7h4pGSJtFkIoQsHqkQkHi05gmwsENS9TLH/R/On6LboCoGwjh14Q5E29aOGZ
XjelhpTuCfMxlTPRGbN4QsJm8CQZ+mCT2evqRiuJ7+blinXxVxol2Ex3GVi9ApZCt06oi/epLb8k
pPmozLYwEjbNJ2+GF9KhCL215R8+V0c0+NIhzgEM8AyCFxZqkE///shmUJSrgsZR/FaZALwxnqcy
iKOM0VzQrucAcsBRtRJ5a2sAVQq0eLAcheXyHEqzG6wYomBF+4fl9gY0QxfXMW1TTJOrndBHHJam
ZtVFx2UY91XpVXTNrTQ4WJUYcFS1LlFCiBzWvyLHUOsVnJjYMhp7bLRVjgtbhzF9KVwfSdBg4zRL
ZWrDAKgWxm+aSZ6eNGUZaM9tFJvqtGHcAV0ysiTJ8VAKBBChoynQ2fR7JlXB4KgzIa0meBaFb0z6
U+tP44VNOG3NdoUeHy1hzpVwltz3wct+ZK0268ML/2MvRBF0DozXV8LlxZjUNVLHwwG70QIinV4T
VVdDR4cy9WkNRhOq4DGj19vH4zXfKE3fUNraQB1HTRSpvZ+B1+ToKe5HvJ1ztO2oxlneR0+ZTAF5
kkjwV1QYUlKD0YsCpZUSMUJmdQ0NBo4Nk6GwvVeUsDjTSatSoQ9M5kKTm4sFRjw6p8PIiDum6Wv3
Qed3jdwHthZ8CuPId4SnQwJPFrKN/R2mzoiqjJsC0YK+N9jwWwXLRRnTQKmKeOOZX63pb5u4Zzke
QBUkghX5ncTiXqe5iieC7F57T0xubPr3sV1DcOpdg8yQ8W2AM33fHwSqFGgb29494PIcaIV0dkOO
GCCuphuF1RgOdEjAs0+vzMAlC5ddFsSC68XosL0Rfc5oQeOX0BuhLuhQBrYFoT5hRkhmjy5sAkiT
mhCwPQ9Mbo8tc4iXTajqM5Iarc4uXCbUrXlER2DvS6HjL+iWPTgO7TFYKTwFqjJlk0dSzGRWxhVF
08IUbIc4nWyjE8HT8KkJdfgZwSNtRj3WRQ0zh9VVv1/5NQybU2arH6tc+NuNMpuyo7oo0gZCvs9m
LPYIHNLCngkL+isGLDC0OQYuW3WbXp7MI7BJO4xO+dHH6mOxqfWreJIHe7Ziul/nmUZ1rXXtJi9o
ex6euG73VeFoqx+yqihdSFc5VxI1khbvOIfyUCJU/KYy3SRYM5M1K9gH5TCOxwFmAKsHkACUufDl
MhdLczpXnYJiZYU/Tr25XzrNGZJU93GGSGqDM0qxSwW0SY+YOqmgyeTcvIP6ZdY40T3Fw346bxax
zDAraDO8FoOnoJgO2MIFsqmFyKG49DAepJgY4rAqwSxxD8GPOISY+erqJJ4lFGuq0CHFum1DT++g
HmDXUDtQrdfre4ACj+pkJybhRPo40dYQuGMYyHBtSuTNLHs03HGWMq86WZJAnl6dXlpcP5PYmqBK
W2s0Xjs4N82GNQoL8N6Ll9fnU/zko3vJJ2Khb6pP4xLxFBvK9pAqr2hRUYLKHOSpc8VGcUAETShw
C2UIg5CZWMzO7zhmhraJVQLwajZxanfTvARHg4d8U/YLpeqQk7Tp1O8flraOh3Wy6H5yIpnwXDLH
rzV0tmQ/YlLZ9bHsgjJ4Sn0UVZuIJv32Clg2GWJDDLMysWGeGX75RDdqEoJ61Sl7enFyPe3/MG4P
j+789uBu0O7/4P8QQiqnI8o+XkAI0O8fT3o6+OjW4fDAfO8TdwUk7va3JKeQnzi/c0LzdJpZ0Hir
3sdRIQb0w6uxp3/q9av+JZYdMg8gL145HfjJKA157naZf7eiapd57DQXUVwId/yicH+KtQzdRuK+
WoHr1JcdofFO1ZfO8d/GmJt/NKEengT5JiucjqvLi4bwaeHyhTklCOIun0kV3bltcxKobznRRZlX
YmEOrVxSq0S6jCvyFcrlbQNg02/OzBMb4hXOPqLOPLx+MOwd9sbw+N0zUJbF8EjMx6PxQvhjPhqN
j4aTo/kw6I1H4dGCTybhIDyErKvHvgPalyvaDrw2ghdDCnkjUgjwLuRvoLwCV0o7PaBRG04fh+mu
yavTMe58lOkfrulbKMRnVNH48OF/AHeo8W4=
===END CRASH DUMP===

**Comment by caspervanneck** [comment]
@haniokasai  @kametan0730MC  ? what hapend

**Comment by TDMidkwhatisxd** [comment]
is this fork dead? PMMP fixed so many issues + try to stay online in your server for 20 minutes you will crash for sure, and on windows10 it will freeze your  entire pc. I think bluelight have some leaks.

**Comment by poustmal** [comment]
Maybe your plugins are crashing or then idk

**Comment by TDMidkwhatisxd** [comment]
I know this bug, and because of it I abandon bluelight. Spawn a Husk and see magic, all crash.

**Comment by ExaSonit** [comment]
remove slapper plugin

**Comment by ExaSonit** [comment]
try to remove slapper plugin and download the last version of it

**Comment by TDMidkwhatisxd** [comment]
i don't use slapper .-.
