### ISSUE TITLE
i can fix it maby

### ISSUE THREAD

**Issue by caspervanneck** [BlueLightJapan/BlueLight#431]
But you need to trust me and give owner @haniokasai  @kametan0730MC  it wont be abandont i dont let it that hapen

**Comment by caspervanneck** [comment]
I dont whant it plz anser @haniokasai

**Comment by haniokasai** [comment]
i gave you privilage.

**Comment by caspervanneck** [comment]
@haniokasai  what do you mean must i clone it?

**Comment by NFGamerMC** [comment]
@caspervanneck Will kill this. He copies code for, everyone. Ban @haniokasai

**Comment by ExaSonit** [comment]
@NFGamerMC what? This is an abandoned software.. @caspervanneck and other will re-create it

**Comment by haniokasai** [comment]
i gave you permission to edit this repo...

**Comment by caspervanneck** [comment]
@haniokasai  sorry i delete my repo
