### ISSUE TITLE
W10 UI  probleme

### ISSUE THREAD

**Issue by armagadon159753** [BlueLightJapan/BlueLight#433]
When crash anythink with Classic UI  console say 
![screenshot_2017-06-15-19-26-33](https://user-images.githubusercontent.com/25569806/27193940-061ece94-5201-11e7-8979-25308c8dbb2f.png)

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other

**Comment by armagadon159753** [comment]
rip industrie of pocketmine 😢

**Comment by ExaSonit** [comment]
Can you close all your issues armagadon159753 ? Thanks.
