### ISSUE TITLE
Client crash on join

### ISSUE THREAD

**Issue by ZizzyZizzy** [BlueLightJapan/BlueLight#436]
### Issue description
The last working build of BlueLight was from June 11th. EVERY build since then simply crashes the client upon joining.

### Steps to reproduce the issue
git clone https://github.com/BlueLightJapan/BlueLight.git
git submodule update --init

Start the server with the new .phar file, attempt to join with Mobile device. Client crashes with no error.

### OS and versions

* PHP: PHP 7.0.19 (cli) (built: May 30 2017 13:43:57) ( ZTS )
* Server OS: CentOS 6.x
* Game version: Mobile v1.1.2, server build 6e1517a

### Crashdump, backtrace or other files
27.06 10:09:08 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\utils\Binary::writeUnsignedVarLong_64() must be of the type integer, null given, called in phar:///jar/pocketmine/bluelight/1.1.0/BlueLight.phar/src/pocketmine/utils/Binary.php on line 689" (EXCEPTION) in "/src/pocketmine/utils/Binary" at line 728

**Comment by caspervanneck** [comment]
its dead

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other

**Comment by ZizzyZizzy** [comment]
That's what it says on the main page, but someone just added some changes today. I was hopeful that it was coming back from the dead.

Tesseract? Good god, the childish infighting, repo deletions and everything else chaotic over there makes it hard to rely on.

**Comment by ExaSonit** [comment]
Can you close all your issues ZizzyZizzy? Thanks.
