### ISSUE TITLE
Entity\Ocelot ???

### ISSUE THREAD

**Issue by fuyutsuki** [BlueLightJapan/BlueLight#44]
> [21:38:54] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\entity\Ocelot::__construct() must be an instance of pocketmine\level\format\FullChunk, instance of pocketmine\level\format\generic\GenericChunk given, called in D:\PMMP\BlueLight\src\pocketmine\entity\Entity.php on line 550" (EXCEPTION) in "/src/pocketmine/entity/Ocelot" at line 48

**Comment by kametan0730MC** [comment]
いつ出ます？

**Comment by kametan0730MC** [comment]
起動時ですか？

**Comment by fuyutsuki** [comment]
@kametan0730MC 0.16.0からのワールドなので、再生成したら治りました
