### ISSUE TITLE
Paintings not work :( pleace check

### ISSUE THREAD

**Issue by MihaSmit** [BlueLightJapan/BlueLight#449]
We have a plugin that allows you to install images in the framework, after updating to your kernel, this plug-in stopped working. I really hope that you can help me with this question.
(google-interpreter) 

![default](https://user-images.githubusercontent.com/16068635/30783436-fafd9f48-a16c-11e7-9513-91cf449d7fc3.png)
![default](https://user-images.githubusercontent.com/16068635/30783452-3fa5e830-a16d-11e7-9ec9-dc9d93b894a9.png)
Error: "Access to undeclared static property: pocketmine\item\Item::$list" (EXCEPTION) in "plugins/MapImageEngine_v1.0.4.phar/src/FaigerSYS/MapImageEngine/MapImageEngine" at line 66

**Comment by xinghao2003** [comment]
Plugin Problem

**Comment by FaigerSYS** [comment]
You're using outdated version of plugin. Please download the new version
