### ISSUE TITLE
Login timeout error

### ISSUE THREAD

**Issue by linuzo** [BlueLightJapan/BlueLight#54]
Players cannot login get a quit message saying login timeout without even seeing building terrain. 

How to fix is to remove the player.dat fine but then it reproduces after some time. 

Any ideas how to fix or what is causing the corrupt player.dat ??

**Comment by linuzo** [comment]
Causes this

2016-12-28 [22:26:11] [RakLibServer thread/NOTICE]: Blocked 99.187.141.122 for 5 seconds
2016-12-28 [22:25:54] [RakLibServer thread/NOTICE]: Blocked 99.187.141.122 for 5 seconds
2016-12-28 [22:25:39] [RakLibServer thread/NOTICE]: Blocked 99.187.141.122 for 5 seconds
2016-12-28 [22:25:15] [RakLibServer thread/NOTICE]: Blocked 99.187.141.122 for 5 seconds
2016-12-28 [22:24:58] [RakLibServer thread/NOTICE]: Blocked 99.187.141.122 for 5 seconds
2016-12-28 [22:24:42] [RakLibServer thread/NOTICE]: Blocked 99.187.141.122 for 5 seconds

Then if I remove the player.dat file they can connect again..

**Comment by linuzo** [comment]
Since player.dat files are basically gzipped nbt files, they must be getting corrupted somehow causing the error..   Just don't know where to look

**Comment by caspervanneck** [comment]
@linuzo i will check

**Comment by caspervanneck** [comment]
it is working for my

**Comment by linuzo** [comment]
Yeah it doesn't happen every time...  Just sometimes. Its one of those things that is hard to reproduce. Unless you have thousands of players that are connecting and then you hear one of them complain or search logs for blocked

**Comment by Infernus102** [comment]
Someone fix this please

**Comment by Infernus102** [comment]
Remove the blocking

**Comment by caspervanneck** [comment]
Blocked 83.160.205.75 for 5 seconds

@Ogiwara-CostlierRain464 its not fixt yet

**Comment by linuzo** [comment]
Possible fix

https://github.com/linuzo/Krafted-UI/commit/0cee850986e556ef4b72108aa0b01e71869ced91

https://github.com/linuzo/Krafted-UI/commit/9549a176ecc3e9bd921735dd75750ba430cf4be5

**Comment by linuzo** [comment]
Since I updated with that raklib and those changes, I haven't received the error in 12 hours..  I will wait more time to see how it goes.

**Comment by Infernus102** [comment]
Pull request
