### ISSUE TITLE
Server Load spike

### ISSUE THREAD

**Issue by Infernus102** [BlueLightJapan/BlueLight#59]
**_DESCRIPTION:_**
Server load spikes upto 30%, only one player online and only one world loaded

**Comment by caspervanneck** [comment]
plugin bug i tink

**Comment by caspervanneck** [comment]
@Infernus102

**Comment by Infernus102** [comment]
Nope it has like 10-12 other getItemInHand() in other function only this task one doesn't work and it worked on PocketMine and Genisys

**Comment by caspervanneck** [comment]
ok

**Comment by Infernus102** [comment]
and why is the server blocking me for 5 seconds when i try to login, using latest commit

**Comment by caspervanneck** [comment]
yes i have it to

**Comment by Infernus102** [comment]
will my old mcr worlds work on this?

**Comment by caspervanneck** [comment]
i dont know

**Comment by caspervanneck** [comment]
mcr world work i think

**Comment by Infernus102** [comment]
is anyone else having problems with unloading worlds? because it takes a long time to restart

**Comment by nightmare3832** [comment]
$p->getInventory()->getItemInHand();

**Comment by Infernus102** [comment]
also the load is too much and ok

**Comment by Infernus102** [comment]
only one player online and the load spikes upto 30%

**Comment by nightmare3832** [comment]
There are no functions as the getItemInHand() in Player.php.

**Comment by Infernus102** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22660649/21545442/d1cf6ec8-cdfd-11e6-989c-69636d841d3b.png)
