### ISSUE TITLE
Slapper

### ISSUE THREAD

**Issue by Infernus102** [BlueLightJapan/BlueLight#61]
**Error:** Argument 5 passed to pocketmine\Server::updatePlayerListData() must be of the type array, object given, called in /home/multicraft/servers/server6/plugins/Slapper/src/slapper/entities/SlapperHuman.php on line 80
File: /src/pocketmine/Server
Line: 2244
Type: notice

**_Backtrace:_**
0 /src/pocketmine/entity/Entity(1671): slapper\entities\SlapperHuman->spawnTo(pocketmine\Player Player(2))
1 /src/pocketmine/level/format/generic/GenericChunk(463): pocketmine\entity\Entity->spawnToAll(boolean)
2 /src/pocketmine/level/Level(2504): pocketmine\level\format\generic\GenericChunk->initChunk(boolean)
3 /src/pocketmine/level/Level(2178): pocketmine\level\Level->loadChunk(integer -19, integer 61, boolean 1)
4 /src/pocketmine/level/Level(2760): pocketmine\level\Level->getChunk(integer -19, integer 61, boolean 1)
5 /src/pocketmine/Player(863): pocketmine\level\Level->populateChunk(integer -19, integer 61)
6 /src/pocketmine/Player(1726): pocketmine\Player->sendNextChunk(boolean)
7 /src/pocketmine/Server(2459): pocketmine\Player->checkNetwork(boolean)
8 /src/pocketmine/Server(2204): pocketmine\Server->tick(boolean)
9 /src/pocketmine/Server(2085): pocketmine\Server->tickProcessor(boolean)
10 /src/pocketmine/Server(1711): pocketmine\Server->start(boolean)
11 /src/pocketmine/PocketMine(478): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/multicraft/servers/server6/Genisys.phar/, string /home/multicraft/servers/server6/, string /home/multicraft/servers/server6/plugins/)
12 (1): require_once(string phar:///home/multicraft/servers/server6/Genisys.phar/src/pocketmine/PocketMine.php)

**Comment by caspervanneck** [comment]
is slaper update

**Comment by caspervanneck** [comment]
i dont  think so

**Comment by Infernus102** [comment]
It worked with early commits of bluelight

**Comment by Infernus102** [comment]
Wait let me update to latest commit and check

**Comment by caspervanneck** [comment]
nope it have still Blocked 83.160.205.75 for 5 seconds

**Comment by Infernus102** [comment]
Why dont you just remove that blocking feature

**Comment by nightmare3832** [comment]
It's necessary to make Slapper correspond to the latest edition of BlueLight.

**Comment by Infernus102** [comment]
Can you tell what to change

**Comment by nightmare3832** [comment]
It's necessary to do the last 2 prices in the "updatePlayerListData()" like a "new Skin($a, $b)".

Add : use pocketmine/entity/Skin;

**Comment by Infernus102** [comment]
Oh ok let me check and can you remove the block login timeout for 5 seconds because I can't login

**Comment by caspervanneck** [comment]
its already fixt @Infernus102

**Comment by Infernus102** [comment]
ok what to change this line to ?
 $player->server->updatePlayerListData($uuid, $entityId, $this->namedtag["MenuName"] ?? "", $this->skinId, $this->skin, [$player]);
