### ISSUE TITLE
全員のスキンが真っ黒になる

### ISSUE THREAD

**Issue by FUGAMARU** [BlueLightJapan/BlueLight#66]
33624de を使用するとスキンが真っ黒になる
自分の環境だけでなく、他の人の環境でも全員のスキンが黒になることを確認しています。
[画像](https://gyazo.com/445e3f39f5e98fa66f2f30fd4df4fef7)

**Comment by Infernus102** [comment]
Confirmed

**Comment by caspervanneck** [comment]
yes indeed

**Comment by kametan0730MC** [comment]
Thank you for your report
