### ISSUE TITLE
Server Load spike

### ISSUE THREAD

**Issue by Infernus102** [BlueLightJapan/BlueLight#67]
![d1cf6ec8-cdfd-11e6-989c-69636d841d3b](https://cloud.githubusercontent.com/assets/22660649/21548441/6165dfe0-ce12-11e6-8823-bb1b43d6bfe1.png)
See the CPU load and players count, number of worlds is just 1

**Comment by xEnzo31** [comment]
Yeah i think this software are heavy

i always have this message if player > 60 at 1vCore CPU 24GHz with 4GB ram (OVH)
[12:38:33] [Server thread/WARNING]: Can't keep up! Is the server overloaded?

but they won't crashing my server

**Comment by Infernus102** [comment]
Yea it seems heavy

**Comment by Infernus102** [comment]
This could be because of chunk loading for each player

**Comment by caspervanneck** [comment]
Yes that is it @Infernus102

**Comment by Infernus102** [comment]
can someone fix my issues?

**Comment by caspervanneck** [comment]
#58

**Comment by caspervanneck** [comment]
#
