### ISSUE TITLE
Stop/restart

### ISSUE THREAD

**Issue by Infernus102** [BlueLightJapan/BlueLight#69]
Server takes a long time to stop or restart i.e unloading worlds. OS: Linux

**Comment by caspervanneck** [comment]
yes on windows to

**Comment by ZizzyZizzy** [comment]
To clarify, it "hangs" when stopping the server. Pocketmine-MP and Genisys do NOT exhibit the same behavior.

29.12 13:06:26 [Server] Server thread/INFO Unloading level "world"
29.12 13:06:26 [Server] Server thread/INFO Stopping other threads

...then nothing happens as I wait patiently wait for up to 30 seconds before forcefully killing it with -9.

**Comment by Infernus102** [comment]
Yep

**Comment by caspervanneck** [comment]
that is a pmmp bug
