### ISSUE TITLE
Login timeout again

### ISSUE THREAD

**Issue by Infernus102** [BlueLightJapan/BlueLight#75]
![untitled](https://cloud.githubusercontent.com/assets/22660649/21563358/92682f5e-cea7-11e6-9c08-971205e53d38.png)
**It's still happening!!**

**Comment by caspervanneck** [comment]
Not for my

**Comment by Infernus102** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22660649/21563502/106e48ba-cea9-11e6-97d8-b657116af444.png)
Also this

**Comment by KennFatt** [comment]
What is your auth plugin?

**Comment by Infernus102** [comment]
simpleauth

**Comment by KennFatt** [comment]
yea that the problem, try another or fix that plugin. i was fix my simple auth and never had this again

**Comment by Infernus102** [comment]
okay then
