### ISSUE TITLE
Server crash with LiveSigns

### ISSUE THREAD

**Issue by GabboMCPE** [BlueLightJapan/BlueLight#96]
Server create a crushdump with this error:
Error: Nesting level too deep - recursive dependency?
File: /Livesign.phar/src/aliuly/livesigns/ParticleTxt
Line: 174
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: LiveSigns v1.2.1php7

**Comment by caspervanneck** [comment]
plugin problem

**Comment by caspervanneck** [comment]
do you read @GabboMCPE THIS CRASH WAS CAUSED BY A PLUGIN
