### ISSUE TITLE
Fire

### ISSUE THREAD

**Issue by FUGAMARU** [BlueLightJapan/BlueLight#98]
火が引火しません。
軽量化のためだったらすみませんが、サーバーの設定項目に追加するなどの検討をして頂けると幸いです。

**Comment by kametan0730MC** [comment]
引火というのは木材から木材に移る感じですか？

**Comment by FUGAMARU** [comment]
返信遅れてすみません。

それもありますし、可燃ブロックの上に溶岩を置いても燃えません。

**Comment by kametan0730MC** [comment]
了解です

**Comment by YaBoiDevelops** [comment]
EAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKv
